# Overpower

This notebook computes [overpower](https://chunithm.org/intermediate/rating/#overpower-op) using scores from [Kamaitachi](https://kamai.tachi.ac/). To get started, make a copy of this notebook, fill in your Kamaitachi username and select a track list in the boxes below, then click "Run all" above. To refresh, just click it again. You can use the table of contents on the left to browse.

Contact @kyleforkbomb on Discord if you:
- run into any issues running the notebook
- notice any bugs (wrong numbers, wrong track list, etc.)
- want a new table/graph/track list/whatever

## Notes
- This notebook computes overpower using the system introduced in LUMINOUS PLUS, i.e. per-song instead of per-chart.
- This notebook does not track chart constant changes over time, as sourcing this data is hard and it doesn't provide a lot of value.
- Since this notebook computes overpower using beerpsi's chuni penguin data, the chart constants will mostly track the international version.
- If you import to Kamaitachi from a source that does not provide timestamps (notably, official servers 😞), then the time the score was imported to Kamaitachi will be used instead. Depending on how often you import, this may mess up the "Overpower Over Time" chart, but the other features should still work fine.
- You could edit the cells in this section if you
  - want a different track list
  - want a score source other than Kamaitachi


## Acknowledgements
- tluo5458, for making the original [OP tracker](https://docs.google.com/preadsheets/d/1Rfkwi99HT8pXisWP71xUWrPQz4HOghD-dCpOttrrEU8/edit?usp=sharing) sheet this notebook is heavily based on
- beerpsi, for maintaining and serving the [song list](https://chunithm.beerpsi.cc/songs)

In [ ]:
# @title Fetch Scores

import json
import re
import urllib.parse
from pathlib import Path

import polars as pl
import requests
from IPython.display import Javascript

pl.Config.set_tbl_rows(50)
pl.Config.set_tbl_hide_column_data_types(True)
pl.Config.set_tbl_hide_dataframe_shape(True)


# hahahahahahahaha... https://github.com/pola-rs/polars/issues/18102
if "real_get_fmt" not in globals():
  real_get_fmt = pl.polars.PySeries.get_fmt
  def get_fmt(self: pl.polars.PySeries, index: int, str_len_limit: int) -> str:
    fmt = real_get_fmt(self, index, str_len_limit)
    if self.dtype() == pl.String:
      return re.sub(r'(^"|"$)', "", fmt, count=2)
    return fmt
  pl.polars.PySeries.get_fmt = get_fmt

def set_iframe_height():
  display(Javascript('''google.colab.output.setIframeHeight(0, true, {maxHeight: 1000000})'''))
get_ipython().events.register('pre_run_cell', set_iframe_height)

# -------------------- get scores --------------------

username = "Lolergags" # @param {"type":"string","placeholder":"kfb"}

print("Fetching scores...")

r = requests.get(f"https://kamai.tachi.ac/api/v1/users/{urllib.parse.quote(username, safe='')}/games/chunithm/Single/scores/all")
scores_json = r.json()["body"]

print(f"Fetched {len(scores_json['scores'])} scores from Kamaitachi")

kt_diff_map = {
  "BASIC": "BAS",
  "ADVANCED": "ADV",
  "EXPERT": "EXP",
  "MASTER": "MAS",
  "ULTIMA": "ULT",
}

chart_difficulty = {
  chart["chartID"]: kt_diff_map[chart["difficulty"]]
  for chart in scores_json["charts"]
}

scores_df = pl.from_dicts(
  {
    "time": score["timeAchieved"] or score["timeAdded"],
    "id": score["songID"],
    "difficulty": chart_difficulty[score["chartID"]],
    "score": score["scoreData"]["score"],
    "lamp": score["scoreData"]["noteLamp"],
    "service": score["service"],
    "import": score["importType"],
  } | score["scoreData"]["judgements"]
  for score in scores_json["scores"]
).with_columns(
  pl.from_epoch("time", time_unit="ms"),
  lamp_bonus=pl.col("lamp").replace_strict(
    ["NONE", "FULL COMBO", "ALL JUSTICE", "ALL JUSTICE CRITICAL"],
    [0, 500, 1000, 1250],
  ),
)

Fetching scores...
Fetched 6769 scores from Kamaitachi

In [ ]:
# @title Calculate Overpower
# @markdown If you change these settings, you can highlight this cell and press
# @markdown Ctrl+F10 to skip fetching your scores from Kamaitachi and re-run
# @markdown everything else.

def fetch_songs_json():
  p = Path("songs.json")
  if p.is_file():
    print("Using cached songs list")
    return json.loads(p.read_text())
  print("Fetching songs list...")
  r = requests.get("https://chunithm.beerpsi.cc/songs")
  p.write_text(r.text)
  return r.json()

charts_df = pl.from_dicts(
  {
    "id": song["id"],
    "title": song["title"],
    "artist": song["artist"],
    "genre": song["genre"],
    "version": song["version"],
    "difficulty": chart["difficulty"],
    "const": chart["const"],
    "added_version": chart["version"] or song["version"],
    "available_jp": song["availability"]["jp"],
    "available_intl": song["availability"]["intl"],
    "notes": chart["notecounts"]["total"],
  }
  for song in fetch_songs_json()
  for chart in song["charts"]
)

print(f"Loaded {charts_df.height} charts")

# -------------------- build track lists --------------------

versions = [
  "CHUNITHM", "CHUNITHM PLUS", "AIR", "AIR PLUS", "STAR", "STAR PLUS", "AMAZON",
  "AMAZON PLUS", "CRYSTAL", "CRYSTAL PLUS", "PARADISE", "PARADISE LOST", "NEW",
  "NEW PLUS", "SUN", "SUN PLUS", "LUMINOUS", "LUMINOUS PLUS", "VERSE",
  "X-VERSE",
]

versions_df = pl.DataFrame(
  {
    "version_name": versions,
    "version_number": range(len(versions)),
  }
)

tutorials = {50, 81}

# not in AOMN
aomn_remove = {0, 5, 9, 10, 12, 14, 17, 28, 34, 36, 39, 42, 43, 54, 55, 56, 57, 58, 60, 78, 84, 85, 86, 87, 109, 110, 111, 112, 116, 124, 125, 126, 129, 130, 154, 155, 176, 182, 184, 185, 206, 207, 209, 214, 215, 231, 235, 238, 243, 247, 255, 269, 296, 299, 308, 309, 311, 313, 315, 344, 345, 348, 349, 350, 351, 352, 353, 355, 356, 357, 358, 359, 360, 410, 419, 420, 422, 424, 454, 473, 495, 501, 509, 522, 523, 529, 530, 531, 537, 541, 542, 544, 545, 546, 579, 580, 581, 582, 591, 609, 610, 611, 612, 613, 620, 621, 622, 623, 624, 639, 640, 642, 644, 645, 646, 647, 648, 649, 650, 651, 652, 682, 724, 725, 726, 727, 728, 769, 770, 778, 794, 808}

aomn = charts_df.filter(
  ~(pl.col("id").is_in(tutorials | aomn_remove)) & (pl.col("difficulty") != "WE")
)

jp = charts_df.filter(
  ~(pl.col("id").is_in(tutorials))
  & (pl.col("difficulty") != "WE")
  & pl.col("available_jp")
)

intl = charts_df.filter(
  ~(pl.col("id").is_in(tutorials))
  & (pl.col("difficulty") != "WE")
  & pl.col("available_intl")
)

track_list = aomn # @param ["aomn","jp","intl"] {"type":"raw"}
version = "VERSE" # @param ["VERSE","LUMINOUS PLUS","LUMINOUS"] {"type":"string"}
track_list_filtered = (
    track_list.join(versions_df, left_on="added_version", right_on="version_name", how="inner")
    .filter(pl.col("version_number") <= versions.index(version))
  ).drop("version_number", "added_version")

# -------------------- compute overpower --------------------

level_base = pl.col("const") * 10_000
overpower_base_df = (
  scores_df.join(charts_df, on=["id", "difficulty"])
  .with_columns(
    overpower_base=(
      pl.when(pl.col("score") >= 1_007_500)
      .then(level_base + 20_000 + (pl.col("score") - 1_007_500) * 3)
      .otherwise(
        pl.when(pl.col("score") >= 1_005_000)
        .then(level_base + 15_000 + (pl.col("score") - 1_005_000) * 2)
        .otherwise(
          pl.when(pl.col("score") >= 1_000_000)
          .then(level_base + 10_000 + (pl.col("score") - 1_000_000))
          .otherwise(
            pl.when(pl.col("score") >= 975_000)
            .then(level_base + (pl.col("score") - 975_000) * 2 / 5)
            .otherwise(
              pl.when(pl.col("score") >= 900_000)
              .then(
                level_base
                - 50_000
                + (pl.col("score") - 900_000) * 2 / 3
              )
              .otherwise(
                pl.when(pl.col("score") >= 800_000)
                .then(
                  (level_base - 50_000) / 2
                  + (
                    (pl.col("score") - 800_000)
                    * ((level_base - 50_000) / 2)
                  )
                  / 100_000
                )
                .otherwise(
                    pl.when(pl.col("score") >= 500_000)
                    .then(
                      (
                        ((level_base - 50_000) / 2)
                        * (pl.col("score") - 500_000)
                      )
                      / 300_000
                    )
                    .otherwise(0)
                )
              )
            )
          )
        )
      )
      / 2
    )
    .floor()
    .cast(pl.Int64),
  )
  .with_columns(
    overpower_base=pl.when(pl.col("score") >= 975_000)
    .then((pl.col("overpower_base") / 5).floor().cast(pl.Int64) * 5)
    .otherwise((pl.col("overpower_base") / 50).floor().cast(pl.Int64) * 50)
  )
)

lamp_bonus_df = scores_df.group_by("id", "difficulty").agg(pl.max("lamp_bonus"))
overpower_df = (
  overpower_base_df.group_by("id", "difficulty")
  .agg(pl.max("overpower_base"))
  .join(lamp_bonus_df, on=["id", "difficulty"])
  .with_columns(overpower=pl.col("overpower_base") + pl.col("lamp_bonus"))
)

best_scores = scores_df.group_by("id", "difficulty").agg(
  pl.max("score"),
  (pl.col("lamp") == "FULL COMBO").any().alias("fc"),
  (pl.col("lamp") == "ALL JUSTICE").any().alias("aj"),
  (pl.col("lamp") == "ALL JUSTICE CRITICAL").any().alias("ajc"),
)

combo_df = (
  track_list_filtered.join(best_scores, on=["id", "difficulty"], how="left")
  .join(overpower_df, on=["id", "difficulty"], how="left")
  .with_columns(
    pl.col("score").fill_null(0),
    pl.col("overpower").fill_null(0),
    (pl.col("const") * 5 + 15).alias("max_overpower"),
    (pl.col("fc") | pl.col("aj") | pl.col("ajc")).fill_null(False),
    (pl.col("aj") | pl.col("ajc")).fill_null(False),
    pl.col("ajc").fill_null(False),
  )
)

combo_best_difficulty_df = combo_df.group_by("id").agg(
  pl.all().exclude("fc", "aj", "ajc", "max_overpower").sort_by("overpower").last(),
  pl.col("fc", "aj", "ajc").sort_by("const").last(),
  pl.max("max_overpower"),
)

op = (combo_df.group_by("id").agg(pl.max("overpower"))["overpower"].sum()) // 10 / 100
max_op = combo_df.group_by("id").agg(pl.max("max_overpower"))["max_overpower"].sum()

Fetching songs list...
Loaded 7909 charts

In [ ]:
# @title OP tracker import
# @markdown If the OP tracker sheet import script is not working, you can paste
# @markdown this into the "Raw Import" tab instead. Make sure to click the copy
# @markdown button instead of copying it manually.

scores_df.group_by("id", "difficulty").agg(
    pl.max("score"),
    fc=pl.col("lamp").is_in({"FULL COMBO", "ALL JUSTICE", "ALL JUSTICE CRITICAL"}).any(),
    aj=pl.col("lamp").is_in({"ALL JUSTICE", "ALL JUSTICE CRITICAL"}).any(),
).join(charts_df, on=["id", "difficulty"]).select(
    Song="title",
    Diff="difficulty",
    Score="score",
    FC="fc",
    AJ="aj",
).write_csv(separator="\t")

'Song\tDiff\tScore\tFC\tAJ\n天体観測\tMAS\t1009991\ttrue\ttrue\nB.B.K.K.B.K.K.\tMAS\t1006041\tfalse\tfalse\nB.B.K.K.B.K.K.\tULT\t1008154\ttrue\tfalse\nScatman (Ski Ba Bop Ba Dop Bop)\tMAS\t1009904\ttrue\ttrue\nReach For The Stars\tMAS\t1007645\tfalse\tfalse\nReach For The Stars\tULT\t1001152\tfalse\tfalse\n初音ミクの消失\tMAS\t1007240\tfalse\tfalse\n情熱大陸\tMAS\t1009232\ttrue\tfalse\nAll I Want\tMAS\t1009679\ttrue\ttrue\n紅蓮の弓矢\tMAS\t1009810\ttrue\ttrue\nコネクト\tMAS\t1009953\ttrue\ttrue\n空色デイズ\tMAS\t1009879\ttrue\ttrue\n千本桜\tMAS\t1007198\tfalse\tfalse\n千本桜\tULT\t1007538\tfalse\tfalse\nDRAGONLADY\tMAS\t1007205\tfalse\tfalse\ntaboo tears you up\tMAS\t1009197\ttrue\tfalse\ntaboo tears you up\tULT\t1005088\tfalse\tfalse\nナイト・オブ・ナイツ\tMAS\t1009921\ttrue\ttrue\n一触即発☆禅ガール\tMAS\t1006474\tfalse\tfalse\nドーナツホール\tMAS\t1008614\ttrue\tfalse\nタイガーランペイジ\tMAS\t1008534\tfalse\tfalse\nタイガーランペイジ\tULT\t1009142\ttrue\tfalse\nPursuing My True Self\tMAS\t1009945\ttrue\ttrue\nBlue Noise\tMAS\t995455\tfalse\tfalse\n亡國覚醒カタルシス\tMAS\t1009795\ttrue\ttrue\nLapis\tMAS\t1007680\tfalse\tfalse\nLapis\tULT\t1003262\tfalse\tfalse\n届かない恋 \'13\tMAS\t1009948\ttrue\ttrue\n鳥の詩\tMAS\t1009894\ttrue\ttrue\n鳥の詩\tULT\t1009928\ttrue\ttrue\n天ノ弱\tMAS\t1009904\ttrue\ttrue\n天ノ弱\tULT\t1007794\tfalse\tfalse\n1/3の純情な感情\tMAS\t1009884\ttrue\ttrue\nsweet little sister\tMAS\t1009894\ttrue\ttrue\noath sign\tMAS\t1009946\ttrue\ttrue\n太陽曰く燃えよカオス\tMAS\t1009948\ttrue\ttrue\nL9\tMAS\t1000081\tfalse\tfalse\nL9\tULT\t997593\tfalse\tfalse\nBad Apple!! feat.nomico\tMAS\t1009920\ttrue\ttrue\n六兆年と一夜物語\tMAS\t1006213\tfalse\tfalse\n六兆年と一夜物語\tULT\t1008324\tfalse\tfalse\nUnlimited Spark!\tMAS\t1009851\ttrue\ttrue\nUnlimited Spark!\tULT\t1008133\tfalse\tfalse\nエピクロスの虹はもう見えない\tMAS\t1009960\ttrue\ttrue\nMy First Phone\tMAS\t1004683\tfalse\tfalse\nCyberozar\tMAS\t1007755\tfalse\tfalse\nTeriqma\tMAS\t1005332\tfalse\tfalse\nブルーバード\tMAS\t1009780\ttrue\ttrue\n夏祭り\tMAS\t1009930\ttrue\ttrue\nそばかす\tMAS\t1009930\ttrue\ttrue\nSTAY AWAY\tMAS\t1009880\ttrue\ttrue\n魂のルフラン\tMAS\t1009926\ttrue\ttrue\nInvitation\tMAS\t1009880\ttrue\ttrue\nonly my railgun\tMAS\t1009954\ttrue\ttrue\nGOLDEN RULE\tMAS\t1005202\tfalse\tfalse\n名も無い鳥\tMAS\t1009477\ttrue\tfalse\nGate of Fate\tMAS\t994963\tfalse\tfalse\nGate of Fate\tULT\t999906\tfalse\tfalse\n今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～\tMAS\t1006038\tfalse\tfalse\nAnemone\tMAS\t1009774\ttrue\ttrue\nAnemone\tULT\t1007991\tfalse\tfalse\n明るい未来\tMAS\t1006257\tfalse\tfalse\n昵懇レファレンス\tMAS\t1009899\ttrue\ttrue\n昵懇レファレンス\tULT\t1009194\tfalse\tfalse\n乗り切れ受験ウォーズ\tMAS\t1009966\ttrue\ttrue\nThe wheel to the right\tEXP\t1009946\ttrue\ttrue\nThe wheel to the right\tMAS\t1001115\tfalse\tfalse\nSTAR\tMAS\t1002394\tfalse\tfalse\nInfantoon Fantasy\tMAS\t1004809\tfalse\tfalse\nInfantoon Fantasy\tULT\t1004194\tfalse\tfalse\nGenesis\tMAS\t993381\tfalse\tfalse\nMUSIC PЯAYER\tMAS\t1004879\tfalse\tfalse\nMUSIC PЯAYER\tULT\t1005593\tfalse\tfalse\nリリーシア\tMAS\t1009962\ttrue\ttrue\nリリーシア\tULT\t1009977\ttrue\ttrue\nCounselor\tMAS\t1008665\tfalse\tfalse\nCounselor\tULT\t1008373\ttrue\tfalse\nluna blu\tMAS\t1003670\tfalse\tfalse\nケモノガル\tMAS\t1004873\tfalse\tfalse\ncrossing field\tMAS\t1004782\tfalse\tfalse\nＧＯ！ＧＯ！ラブリズム♥\tMAS\t1009854\ttrue\ttrue\nGrab your sword\tMAS\t1009878\ttrue\ttrue\nMemories of Sun and Moon\tMAS\t1003156\tfalse\tfalse\nロストワンの号哭\tMAS\t1003567\tfalse\tfalse\nロストワンの号哭\tULT\t1004684\tfalse\tfalse\nV.I.P\tMAS\t1009953\ttrue\ttrue\n睡蓮花\tMAS\t1009930\ttrue\ttrue\nキラーボール\tMAS\t1009817\ttrue\ttrue\nButter-Fly\tMAS\t1009911\ttrue\ttrue\nThe Concept of Love\tMAS\t1008583\ttrue\tfalse\nJET\tMAS\t1008319\tfalse\tfalse\nJET\tULT\t1008802\ttrue\tfalse\nL\'épisode\tMAS\t1001545\tfalse\tfalse\nYet Another ”drizzly rain”\tMAS\t1008810\ttrue\tfalse\n最終鬼畜妹・一部声\tMAS\t1001984\tfalse\tfalse\n蒼空に舞え、墨染の桜\tMAS\t1009190\ttrue\tfalse\nセツナトリップ\tMAS\t1007443\tfalse\tfalse\n砂漠のハンティングガール♡\tMAS\t1005962\tfalse\tfalse\n砂漠のハンティングガール♡\tULT\t1002834\tfalse\tfalse\nチルノのパーフェクトさんすう教室\tMAS\t1006015\tfalse\tfalse\nHelp me, ERINNNNNN!!（Band ver.）\tMAS\t1009880\ttrue\ttrue\n魔理沙は大変なものを盗んでいきました\tMAS\t1008831\ttrue\tfalse\n魔理沙は大変なものを盗んでいきました\tULT\t998219\tfalse\tfalse\n言ノ葉カルマ\tMAS\t1004482\tfalse\tfalse\n言ノ葉カルマ\tULT\t1002295\tfalse\tfalse\nAfter the rain\tMAS\t1008010\tfalse\tfalse\nAfter the rain\tULT\t1009543\ttrue\tfalse\nTango Rouge\tMAS\t1004590\tfalse\tfalse\nTuning Rangers\tMAS\t1005701\tfalse\tfalse\nエンドマークに希望と涙を添えて\tMAS\t991541\tfalse\tfalse\nとーきょー全域★アキハバラ？\tMAS\t1005234\tfalse\tfalse\novercome\tMAS\t1009759\ttrue\ttrue\n宛城、炎上！！\tMAS\t1000091\tfalse\tfalse\nWe Gonna Journey\tMAS\t1006064\tfalse\tfalse\nWe Gonna Journey\tULT\t1001970\tfalse\tfalse\nThe ether\tMAS\t1004494\tfalse\tfalse\nEmotions\tMAS\t1009958\ttrue\ttrue\nMagia\tMAS\t1009971\ttrue\ttrue\nstaple stable\tMAS\t1009832\ttrue\ttrue\nマジLOVE1000%\tMAS\t1009910\ttrue\ttrue\nストリーミングハート\tMAS\t1009886\ttrue\ttrue\nストリーミングハート\tULT\t1006250\tfalse\tfalse\nSweet Devil\tMAS\t1009190\ttrue\tfalse\nDreaming\tMAS\t1009809\ttrue\ttrue\n君の知らない物語\tMAS\t1009988\ttrue\ttrue\nM.S.S.Planet\tMAS\t1009154\ttrue\tfalse\n腐れ外道とチョコレゐト\tMAS\t1001698\tfalse\tfalse\n腐れ外道とチョコレゐト\tULT\t1001821\tfalse\tfalse\nアウターサイエンス\tMAS\t1008322\tfalse\tfalse\n四次元跳躍機関\tMAS\t1007782\tfalse\tfalse\n東方妖々夢 ～the maximum moving about～\tMAS\t1005880\tfalse\tfalse\n少女幻葬戦慄曲\u3000～\u3000Necro Fantasia\tMAS\t1006556\tfalse\tfalse\n橙の幻想郷音頭\tMAS\t1009863\ttrue\ttrue\n夏影\tMAS\t1005665\tfalse\tfalse\nLittle Busters! ～TV animation ver.～\tMAS\t1009922\ttrue\ttrue\nHeart To Heart\tMAS\t1009983\ttrue\ttrue\nThe Formula\tMAS\t1003699\tfalse\tfalse\nHacking to the Gate\tMAS\t1009958\ttrue\ttrue\nスカイクラッドの観測者\tMAS\t1009946\ttrue\ttrue\nチルドレンレコード\tMAS\t1003319\tfalse\tfalse\nイカサマライフゲイム\tMAS\t1008916\tfalse\tfalse\nイカサマライフゲイム\tULT\t1007358\tfalse\tfalse\nシリョクケンサ\tMAS\t1009935\ttrue\ttrue\nHAELEQUIN (Original Remaster)\tMAS\t1003060\tfalse\tfalse\nVallista\tMAS\t1003310\tfalse\tfalse\nÄventyr\tMAS\t1003103\tfalse\tfalse\nAngel dust\tMAS\t1006072\tfalse\tfalse\nconflict\tMAS\t1004293\tfalse\tfalse\nGuilty\tMAS\t1009780\ttrue\ttrue\nGuilty\tULT\t1005371\tfalse\tfalse\n閃鋼のブリューナク\tMAS\t990764\tfalse\tfalse\nAltale\tMAS\t1002550\tfalse\tfalse\nODDS&ENDS\tMAS\t1009960\ttrue\ttrue\nODDS&ENDS\tULT\t1009677\ttrue\tfalse\nAragami\tMAS\t1006937\tfalse\tfalse\nChange Our MIRAI！\tMAS\t1009917\ttrue\ttrue\n夕暮れワンルーム\tMAS\t1009899\ttrue\ttrue\nこころここから\tMAS\t1009939\ttrue\ttrue\nTheme of SeelischTact\tMAS\t1008651\tfalse\tfalse\nTheme of SeelischTact\tULT\t1004902\tfalse\tfalse\n緋色のDance\tMAS\t1007709\tfalse\tfalse\nbrilliant better\tMAS\t1008543\tfalse\tfalse\nbrilliant better\tULT\t1008039\tfalse\tfalse\nAlma\tMAS\t1001546\tfalse\tfalse\nGustav Battle\tMAS\t1003102\tfalse\tfalse\nGustav Battle\tULT\t991343\tfalse\tfalse\nSAVIOR OF SONG\tMAS\t1000843\tfalse\tfalse\nブルー・フィールド\tMAS\t1009880\ttrue\ttrue\nFREELY TOMORROW\tMAS\t1009883\ttrue\ttrue\nギガンティックO.T.N\tMAS\t1002258\tfalse\tfalse\nフォルテシモBELL\tMAS\t1009824\ttrue\ttrue\nジングルベル\tMAS\t1007348\tfalse\tfalse\nジングルベル\tULT\t1000617\tfalse\tfalse\n言ノ葉遊戯\tMAS\t1009941\ttrue\ttrue\n私の中の幻想的世界観及びその顕現を想起させたある現実での出来事に関する一考察\tMAS\t1005750\tfalse\tfalse\n幾四音-Ixion-\tMAS\t1009900\ttrue\ttrue\n幾四音-Ixion-\tULT\t1007507\tfalse\tfalse\nぼくらの16bit戦争\tMAS\t1007103\tfalse\tfalse\n裏表ラバーズ\tMAS\t1009816\ttrue\ttrue\n裏表ラバーズ\tULT\t1009202\ttrue\tfalse\n脳漿炸裂ガール\tMAS\t1002543\tfalse\tfalse\n脳漿炸裂ガール\tULT\t1001855\tfalse\tfalse\nネトゲ廃人シュプレヒコール\tMAS\t1008212\tfalse\tfalse\nネトゲ廃人シュプレヒコール\tULT\t1006829\tfalse\tfalse\nelegante\tMAS\t1009150\ttrue\tfalse\nelegante\tULT\t1004551\tfalse\tfalse\nDETARAME ROCK&ROLL THEORY\tMAS\t1009865\ttrue\ttrue\nXL TECHNO\tMAS\t1002089\tfalse\tfalse\nHalcyon\tMAS\t1003903\tfalse\tfalse\nHalcyon\tULT\t999014\tfalse\tfalse\nDance!\tMAS\t1009927\ttrue\ttrue\nJimang Shot\tMAS\t1003821\tfalse\tfalse\nstella=steLLa\tMAS\t1002160\tfalse\tfalse\nすろぉもぉしょん\tMAS\t1009886\ttrue\ttrue\nすろぉもぉしょん\tULT\t1005140\tfalse\tfalse\n怒槌\tEXP\t1005165\tfalse\tfalse\n怒槌\tMAS\t994330\tfalse\tfalse\nユクエシレズ\tMAS\t1009822\ttrue\ttrue\nWHITE ALBUM Live at Campus Fes\tEXP\t1009953\ttrue\ttrue\nWHITE ALBUM Live at Campus Fes\tMAS\t1009937\ttrue\ttrue\neuphoric field（English）\tMAS\t1009949\ttrue\ttrue\nLast regrets\tMAS\t1009951\ttrue\ttrue\n楽園の翼\tMAS\t1009953\ttrue\ttrue\nってゐ！\u3000～えいえんてゐVer～\tMAS\t1009964\ttrue\ttrue\n患部で止まってすぐ溶ける～狂気の優曇華院\tMAS\t1004677\tfalse\tfalse\n患部で止まってすぐ溶ける～狂気の優曇華院\tULT\t1002303\tfalse\tfalse\nひれ伏せ愚民どもっ！\tMAS\t1006967\ttrue\tfalse\nエテルニタス・ルドロジー\tMAS\t1007073\tfalse\tfalse\n幽闇に目醒めしは\tMAS\t1009873\ttrue\ttrue\nStarlight Vision\tMAS\t1008212\tfalse\tfalse\nClub Ibuki in Break All\tMAS\t1009121\tfalse\tfalse\nPhantasm Brigade\tMAS\t1009394\ttrue\tfalse\n永遠のメロディ\tMAS\t1009187\tfalse\tfalse\nFREEDOM DiVE\tMAS\t1001318\tfalse\tfalse\nJack-the-Ripper◆\tMAS\t1000510\tfalse\tfalse\nAVALON\tMAS\t1003178\tfalse\tfalse\nハート・ビート\tMAS\t1009087\tfalse\tfalse\n無敵We are one!!\tMAS\t1006147\tfalse\tfalse\nContrapasso -inferno-\tMAS\t1000305\tfalse\tfalse\nGEMINI -C-\tMAS\t1000737\tfalse\tfalse\nFLOWER\tMAS\t1006372\tfalse\tfalse\nFLOWER\tULT\t1006527\tfalse\tfalse\nちくわパフェだよ☆CKP\tMAS\t1009908\ttrue\ttrue\nちくわパフェだよ☆CKP\tULT\t1002940\tfalse\tfalse\nSNIPE WHOLE\tMAS\t1006124\tfalse\tfalse\nSigns Of Love (“Never More” ver.)\tMAS\t1009328\ttrue\tfalse\nYour Affection (Daisuke Asakura Remix)\tMAS\t1009891\ttrue\ttrue\nSAMBISTA\tMAS\t1005570\ttrue\tfalse\n君色シグナル\tMAS\t1009897\ttrue\ttrue\nアスノヨゾラ哨戒班\tMAS\t1006995\tfalse\tfalse\nアスノヨゾラ哨戒班\tULT\t1006715\tfalse\tfalse\n天樂\tMAS\t1008282\ttrue\tfalse\nいろは唄\tMAS\t1005841\tfalse\tfalse\n星屑ユートピア\tMAS\t1009931\ttrue\ttrue\n青春はNon-Stop！\tMAS\t1009966\ttrue\ttrue\nFalling Roses\tMAS\t1009915\ttrue\ttrue\n放課後革命\tMAS\t1008530\tfalse\tfalse\n楽園ファンファーレ\tMAS\t1009891\ttrue\ttrue\nサウンドプレイヤー\tMAS\t1009442\ttrue\tfalse\n玩具狂奏曲 -終焉-\tEXP\t1007556\tfalse\tfalse\n玩具狂奏曲 -終焉-\tMAS\t1000326\tfalse\tfalse\n如月アテンション\tMAS\t1005729\tfalse\tfalse\nMr. Wonderland\tMAS\t1007035\tfalse\tfalse\nカミサマネジマキ\tMAS\t1004342\tfalse\tfalse\n恋愛裁判\tMAS\t1009884\ttrue\ttrue\nウミユリ海底譚\tMAS\t1005536\tfalse\tfalse\nGarakuta Doll Play\tEXP\t1009512\ttrue\tfalse\nGarakuta Doll Play\tMAS\t1002550\tfalse\tfalse\n洗脳\tMAS\t1009923\ttrue\ttrue\nこのふざけた素晴らしき世界は、僕の為にある\tMAS\t1009257\ttrue\tfalse\n紅華刑\tMAS\t1003315\tfalse\tfalse\nHyperion\tMAS\t1009836\ttrue\ttrue\nカラフル。\tMAS\t1009927\ttrue\ttrue\nElemental Creation\tMAS\t1001865\tfalse\tfalse\nElemental Creation\tULT\t1000779\tfalse\tfalse\nアルストロメリア\tMAS\t1006885\tfalse\tfalse\nアルストロメリア\tULT\t1006270\tfalse\tfalse\nDevastating Blaster\tMAS\t996168\tfalse\tfalse\nファッとして桃源郷\tMAS\t1005135\tfalse\tfalse\nフレンズ\tMAS\t1009887\ttrue\ttrue\n夜咄ディセイブ\tMAS\t1009422\ttrue\tfalse\nシュガーソングとビターステップ\tMAS\t1009060\ttrue\tfalse\n回レ！雪月花\tMAS\t1007857\tfalse\tfalse\n回レ！雪月花\tULT\t1008827\ttrue\tfalse\nHelp me, あーりん！\tMAS\t1009950\ttrue\ttrue\nなるとなぎのパーフェクトロックンロール教室\tMAS\t1009293\ttrue\tfalse\n絶世スターゲイト\tMAS\t1009940\ttrue\ttrue\nSchrecklicher Aufstand\tMAS\t995603\tfalse\tfalse\nドライヴ・オン・ザ・レインボー\tMAS\t1006990\tfalse\tfalse\nPhilosopher\tMAS\t1006162\tfalse\tfalse\nCrazy ∞ nighT\tMAS\t1008187\tfalse\tfalse\n愛迷エレジー\tMAS\t1008751\ttrue\tfalse\nWarcry\tMAS\t1009461\tfalse\tfalse\nその群青が愛しかったようだった\tMAS\t1009890\ttrue\ttrue\n激情！ミルキィ大作戦\tMAS\t1010000\ttrue\ttrue\n札付きのワル\u3000～マイケルのうた～\tMAS\t1001991\tfalse\tfalse\nBOKUTO\tMAS\t1007844\tfalse\tfalse\nTiamaT:F minor\tEXP\t997502\tfalse\tfalse\nTiamaT:F minor\tMAS\t1002138\tfalse\tfalse\nOshama Scramble! (Cranky Remix)\tMAS\t1007733\tfalse\tfalse\nD.E.A.D.L.Y.\tMAS\t1006339\tfalse\tfalse\nロボットプラネットユートピア\tMAS\t1009593\ttrue\tfalse\nTidal Wave\tMAS\t1002803\tfalse\tfalse\nHand in Hand\tMAS\t1009948\ttrue\ttrue\nMy Dearest Song\tMAS\t1005805\tfalse\tfalse\n猫祭り\tMAS\t1009935\ttrue\ttrue\nゲシュタルト！テスト期間！！\tMAS\t1006646\tfalse\tfalse\n心象蜃気楼\tMAS\t1009915\ttrue\ttrue\nBang Babang Bang!!!\tMAS\t1009757\ttrue\ttrue\n僕らの翼\tMAS\t1010000\ttrue\ttrue\nエンヴィキャットウォーク\tMAS\t1008832\tfalse\tfalse\n鬼KYOKAN\tMAS\t1009488\ttrue\tfalse\n有頂天ビバーチェ\tMAS\t1009853\ttrue\ttrue\nビバハピ\tMAS\t1009967\ttrue\ttrue\n願い星\tMAS\t1009932\ttrue\ttrue\n愛言葉\tMAS\t1009847\ttrue\ttrue\n後夜祭\tMAS\t1006250\tfalse\tfalse\nTRUST\tMAS\t1001563\tfalse\tfalse\nからくりピエロ\tMAS\t1009773\ttrue\ttrue\n深海少女\tMAS\t1009781\ttrue\ttrue\nリモコン\tMAS\t1009933\ttrue\ttrue\nラクガキスト\tMAS\t1009319\ttrue\tfalse\nアカツキアライヴァル\tMAS\t1009809\ttrue\ttrue\n神曲\tMAS\t1008618\tfalse\tfalse\n幸せになれる隠しコマンドがあるらしい\tMAS\t1008450\tfalse\tfalse\nメルト\tMAS\t1009957\ttrue\ttrue\nTell Your World\tMAS\t1009891\ttrue\ttrue\nロミオとシンデレラ\tMAS\t1009887\ttrue\ttrue\nFirst Twinkle\tMAS\t1009966\ttrue\ttrue\nウソラセラ\tMAS\t1009306\ttrue\tfalse\n檄!帝国華撃団\tMAS\t1009861\ttrue\ttrue\nKronos\tMAS\t1008136\ttrue\tfalse\n月に叢雲華に風\tMAS\t1009126\ttrue\tfalse\nインビジブル\tMAS\t1005736\tfalse\tfalse\n人生リセットボタン\tMAS\t1009039\ttrue\tfalse\n響\tMAS\t1008420\tfalse\tfalse\nかくしん的☆めたまるふぉ～ぜっ!\tMAS\t1009955\ttrue\ttrue\n風仁雷仁\tMAS\t1005936\tfalse\tfalse\n風仁雷仁\tULT\t1001554\tfalse\tfalse\nPRIVATE SERVICE\tMAS\t1008638\tfalse\tfalse\nPRIVATE SERVICE\tULT\t996758\tfalse\tfalse\nsecret base ～君がくれたもの～ (10 years after Ver.)\tMAS\t1009879\ttrue\ttrue\nNo Routine\tMAS\t1007154\tfalse\tfalse\n白い雪のプリンセスは\tMAS\t1009970\ttrue\ttrue\nStrahv\tMAS\t1006915\tfalse\tfalse\nDreams Dreams:Kids Ver.\tMAS\t1009929\ttrue\ttrue\nIn The Blue Sky \'01\tMAS\t1009930\ttrue\ttrue\n幻想のサテライト\tMAS\t1002448\tfalse\tfalse\n凛として咲く花の如く\tMAS\t1009464\ttrue\tfalse\n凛として咲く花の如く\tULT\t1002425\tfalse\tfalse\nPaqqin\tMAS\t1009490\ttrue\tfalse\nfake!fake!\tMAS\t1009965\ttrue\ttrue\nRising Hope\tMAS\t1008237\tfalse\tfalse\n覚醒楽奏メタフィクション\tMAS\t1007096\tfalse\tfalse\nBe My Friend\tMAS\t1009856\ttrue\ttrue\nぶいえす!!らいばる!!\tMAS\t1006923\tfalse\tfalse\nひだまりデイズ\tMAS\t1009958\ttrue\ttrue\nThis game\tMAS\t1009870\ttrue\ttrue\nオラシオン\tMAS\t1009921\ttrue\ttrue\nみくみくにしてあげる♪【してやんよ】\tMAS\t1009982\ttrue\ttrue\nAir\tMAS\t998254\tfalse\tfalse\nAir\tULT\t999809\tfalse\tfalse\nDataErr0r\tMAS\t1008639\tfalse\tfalse\nSay A Vengeance\tMAS\t1004322\tfalse\tfalse\n010\tMAS\t1008571\tfalse\tfalse\nERIS -Legend of Gaidelia-\tMAS\t1007440\tfalse\tfalse\nERIS -Legend of Gaidelia-\tULT\t996868\tfalse\tfalse\nImperishable Night 2006 (2016 Refine)\tMAS\t1005620\tfalse\tfalse\nDreadnought\tEXP\t993089\tfalse\tfalse\nDreadnought\tMAS\t1001904\tfalse\tfalse\nDreadnought\tULT\t991572\tfalse\tfalse\nSTAGER\tMAS\t1007427\tfalse\tfalse\nHer Majesty\tMAS\t1001067\tfalse\tfalse\nSakura Fubuki\tMAS\t1001348\tfalse\tfalse\nJULIAN\tMAS\t1008056\tfalse\tfalse\n★LittlE HearTs★\tMAS\t993995\tfalse\tfalse\nSTAIRWAY TO GENERATION\tMAS\t1004349\tfalse\tfalse\nドキドキDREAM!!!\tMAS\t1006578\tfalse\tfalse\nドキドキDREAM!!!\tULT\t1007127\tfalse\tfalse\n猛進ソリストライフ！\tMAS\t1004000\tfalse\tfalse\n猛進ソリストライフ！\tULT\t1002568\tfalse\tfalse\n空威張りビヘイビア\tMAS\t1009657\ttrue\tfalse\n空威張りビヘイビア\tULT\t1005812\tfalse\tfalse\nOshama Scramble!\tMAS\t1008051\tfalse\tfalse\nOshama Scramble!\tULT\t1002171\tfalse\tfalse\nFLOATED CALM\tMAS\t1009603\ttrue\tfalse\nSupersonic Generation\tMAS\t1003149\tfalse\tfalse\nシジョウノコエ VOCALO ver.\tMAS\t1006322\tfalse\tfalse\nTic Tac DREAMIN’\tMAS\t1009927\ttrue\ttrue\nSPICY SWINGY STYLE\tMAS\t1009024\ttrue\tfalse\nRevolutionGame\tMAS\t1009877\ttrue\ttrue\nStill\tMAS\t1007951\tfalse\tfalse\nおまかせ！！トラブルメイ娘☆とれびちゃん\tMAS\t1005987\tfalse\tfalse\nオススメ☆♂♀☆でぃすとぴあ\tMAS\t1000153\tfalse\tfalse\nDaydream café\tMAS\t1009853\ttrue\ttrue\nDaydream café\tULT\t1009940\ttrue\ttrue\nノーポイッ!\tMAS\t1009949\ttrue\ttrue\nムーンライト伝説\tMAS\t1009939\ttrue\ttrue\nJumping!!\tMAS\t1009846\ttrue\ttrue\n極上スマイル\tMAS\t1009969\ttrue\ttrue\nFEEL×ALIVE\tMAS\t1009133\ttrue\tfalse\nぶぉん！ぶぉん！らいど・おん！\tMAS\t1005623\tfalse\tfalse\nStar☆Glitter\tMAS\t1009217\ttrue\tfalse\nH-A-J-I-M-A-R-I-U-T-A-!!\tMAS\t1009917\ttrue\ttrue\nラブリー☆えんじぇる!!\tMAS\t1009973\ttrue\ttrue\nだんご大家族\tMAS\t1009925\ttrue\ttrue\nクローバー♣かくめーしょん\tMAS\t1007642\ttrue\tfalse\nぐーちょきパレード\tMAS\t1009988\ttrue\ttrue\nMy Soul,Your Beats!\tMAS\t1009980\ttrue\ttrue\nThousand Enemies\tMAS\t1009943\ttrue\ttrue\n夢想歌\tMAS\t1009919\ttrue\ttrue\nFace of Fact\tMAS\t1008658\ttrue\tfalse\ntrue my heart -Lovable mix-\tMAS\t1009937\ttrue\ttrue\n桜ノ雨\tMAS\t1009796\ttrue\ttrue\nいーあるふぁんくらぶ\tMAS\t1009926\ttrue\ttrue\nおこちゃま戦争\tMAS\t1008538\tfalse\tfalse\nエイリアンエイリアン\tMAS\t1009916\ttrue\ttrue\n虎視眈々\tMAS\t1008955\ttrue\tfalse\nアンハッピーリフレイン\tMAS\t1008387\ttrue\tfalse\nすきなことだけでいいです\tMAS\t1002784\tfalse\tfalse\nデリヘル呼んだら君が来た\tMAS\t1008700\tfalse\tfalse\nチュルリラ・チュルリラ・ダッダッダ！\tMAS\t1009603\ttrue\tfalse\nだんだん早くなる\tMAS\t1009862\ttrue\ttrue\nECHO\tEXP\t1009982\ttrue\ttrue\nECHO\tMAS\t1007228\tfalse\tfalse\n泡沫、哀のまほろば\tMAS\t1009898\ttrue\ttrue\n愛き夜道 feat. ランコ、雨天決行\tMAS\t1007978\tfalse\tfalse\nStarlight Dance Floor\tMAS\t1009851\ttrue\ttrue\nWitches night\tMAS\t1009898\ttrue\ttrue\nHelp me, ERINNNNNN!! -Cranky remix-\tMAS\t1007672\tfalse\tfalse\n仙酌絶唱のファンタジア\tMAS\t1009136\tfalse\tfalse\nキュアリアス光吉古牌\u3000－祭－\tMAS\t1008515\ttrue\tfalse\nEvans\tMAS\t1004256\tfalse\tfalse\nEvans\tULT\t995829\tfalse\tfalse\n神威\tEXP\t1000541\tfalse\tfalse\n神威\tMAS\t1001495\tfalse\tfalse\nGOODTEK\tMAS\t1007508\tfalse\tfalse\nName of oath\tMAS\t1003209\tfalse\tfalse\nBird Sprite\tMAS\t1006503\tfalse\tfalse\nオモイヨシノ\tMAS\t1009931\ttrue\ttrue\nDengeki Tube\tMAS\t991077\tfalse\tfalse\n若い力 -SEGA HARD GIRLS MIX-\tMAS\t1009904\ttrue\ttrue\nレッツゴー!陰陽師\tMAS\t1009907\ttrue\ttrue\nあねぺったん\tMAS\t1009932\ttrue\ttrue\nLike the Wind [Reborn]\tMAS\t1007825\tfalse\tfalse\n天国と地獄 -言ノ葉リンネ-\tMAS\t1009867\ttrue\ttrue\n最愛テトラグラマトン\tMAS\t1009315\ttrue\tfalse\n悪戯\tMAS\t1009547\ttrue\tfalse\nりばーぶ\tMAS\t1009910\ttrue\ttrue\nBarbed Eye\tMAS\t1008165\tfalse\tfalse\n分からない\tMAS\t1007784\tfalse\tfalse\n相思創愛\tMAS\t1008542\tfalse\tfalse\n混沌を越えし我らが神聖なる調律主を讃えよ\tEXP\t1008158\ttrue\tfalse\n混沌を越えし我らが神聖なる調律主を讃えよ\tMAS\t992160\tfalse\tfalse\nFinite\tMAS\t996187\tfalse\tfalse\nMY LIBERATION\tMAS\t1007790\tfalse\tfalse\n地球最後の告白を\tMAS\t1007743\tfalse\tfalse\nThe wheel to the Night ～インド人が夢に!?～\tMAS\t1007614\tfalse\tfalse\nWe Gonna Party -Feline Groove Mix-\tMAS\t1006302\tfalse\tfalse\nThrough The Tower\tMAS\t1008490\tfalse\tfalse\nRedo\tMAS\t1008777\tfalse\tfalse\nRedo\tULT\t1007230\tfalse\tfalse\nSAKURAスキップ\tMAS\t1009968\ttrue\ttrue\nNow Loading!!!!\tMAS\t1009236\ttrue\tfalse\n前前前世\tMAS\t1009985\ttrue\ttrue\nMEMORIA\tMAS\t1009811\ttrue\ttrue\nMIRU key way\tMAS\t1009902\ttrue\ttrue\n華鳥風月\tMAS\t1009850\ttrue\ttrue\n儚きもの人間\tMAS\t1008278\ttrue\tfalse\nAleph-0\tEXP\t1005313\tfalse\tfalse\nAleph-0\tMAS\t1000608\tfalse\tfalse\nAleph-0\tULT\t995918\tfalse\tfalse\nBlack Lotus\tMAS\t1005214\tfalse\tfalse\nＧＯ！ＧＯ！ラブリズム♥ ～あーりん書類審査通過記念Ver.～\tMAS\t1009506\ttrue\tfalse\nSession High⤴\tMAS\t1009333\tfalse\tfalse\n光線チューニング\tMAS\t1009970\ttrue\ttrue\n立川浄穢捕物帳\tMAS\t1003083\tfalse\tfalse\n眠れぬ夜君を想フ\tMAS\t1006457\tfalse\tfalse\nJIGOKU STATION CENTRAL GATE\tMAS\t1008835\ttrue\tfalse\nJIGOKU STATION CENTRAL GATE\tULT\t1008344\tfalse\tfalse\nPinqPiq\tMAS\t1007662\tfalse\tfalse\nトリスメギストス\tMAS\t1007916\tfalse\tfalse\nWE GOTTA SOUL\tMAS\t1008859\tfalse\tfalse\n哀しみ集め\tMAS\t1007890\tfalse\tfalse\nキラメケ→Shoot it Now!\tMAS\t1003523\tfalse\tfalse\nKattobi KEIKYU Rider\tMAS\t1003863\tfalse\tfalse\nGlorious Crown (tpz over-Over-OVERCUTE REMIX)\tEXP\t1007957\tfalse\tfalse\nGlorious Crown (tpz over-Over-OVERCUTE REMIX)\tMAS\t1005792\tfalse\tfalse\nエレクトロサチュレイタ\tMAS\t1009909\ttrue\ttrue\nPalette\tMAS\t1007963\tfalse\tfalse\nアマツキツネ\tMAS\t1009917\ttrue\ttrue\nパーフェクト生命\tMAS\t1009974\ttrue\ttrue\nのぼれ！すすめ！高い塔\tMAS\t1001697\tfalse\tfalse\n害虫\tMAS\t1008824\tfalse\tfalse\nガチャガチャきゅ～と・ふぃぎゅ@メイト\tMAS\t1003262\tfalse\tfalse\nVampire\tMAS\t1008739\tfalse\tfalse\nVampire\tULT\t996755\tfalse\tfalse\nケロ⑨destiny\tMAS\t1008988\ttrue\tfalse\nLast Moments\tMAS\t1005618\tfalse\tfalse\n風に乗せた願い\tMAS\t1009057\tfalse\tfalse\n天狗の落とし文 feat. ｙｔｒ\tMAS\t1009324\ttrue\tfalse\n星色夜空\tMAS\t1009922\ttrue\ttrue\n物凄い勢いでけーねが物凄いうた\tMAS\t1009978\ttrue\ttrue\n物凄い勢いでけーねが物凄いうた\tULT\t1005929\tfalse\tfalse\nWake up Dreamer\tMAS\t1008434\tfalse\tfalse\nWorld Vanquisher\tEXP\t1000609\tfalse\tfalse\nWorld Vanquisher\tMAS\t997053\tfalse\tfalse\nmacrocosmos\tEXP\t1005106\tfalse\tfalse\nmacrocosmos\tMAS\t999500\tfalse\tfalse\nIudicium\tMAS\t996955\tfalse\tfalse\nTwice up Scenery\tMAS\t1004093\tfalse\tfalse\n奏者はただ背中と提琴で語るのみ\tM

# Aggregations

In [ ]:
# @title All Overpower

print(f"{op} / {max_op} ({int(op / max_op * 10000) / 100}%)\n")

overpower_over_time = (
  overpower_base_df.join(track_list_filtered, on=["id", "difficulty"])
  .sort("time")
  .with_columns(
    overpower=(
      pl.col("overpower_base").cum_max() + pl.col("lamp_bonus").cum_max()
    ).over("id", "difficulty")
  )
  .with_columns(
    overpower_gain=(
      pl.col("overpower")
      - (pl.col("overpower").cum_max().shift(1, fill_value=0).over("id"))
    ).clip(0)
  )
  .select(
    "time",
    pl.col("overpower_gain").cum_sum().alias("overpower") // 10 / 100,
  )
)

overpower_over_time.group_by_dynamic("time", every="1d").agg(
  pl.last("overpower")
).plot.line(x="time", y="overpower").properties(
  title="Overpower Over Time", width=800, height=400
)

124564.08 / 131427.5 (94.77%)

alt.Chart(...)

In [ ]:
# @title Overpower by Level

def overpower_by(df: pl.DataFrame, expr: pl.Expr) -> pl.DataFrame:
  return (
    df.group_by(expr)
    .agg(
      pl.len().alias("#"),
      (pl.col("score") > 0).sum().alias("played"),
      pl.sum("fc"),
      pl.sum("aj"),
      pl.sum("ajc"),
      ((pl.col("overpower")).sum() // 10 / 100).round(2).alias("overpower"),
      pl.sum("max_overpower"),
      ((pl.col("overpower") > 0) * pl.col("max_overpower"))
      .sum()
      .alias("filtered_max_overpower"),
    )
    .with_columns(
      (pl.col("overpower") / pl.col("max_overpower") * 100)
      .round(3)
      .alias("overpower_percent"),
      (pl.col("overpower") / pl.col("filtered_max_overpower") * 100)
      .round(3)
      .alias("filtered_overpower_percent"),
    )
    .select(
      pl.nth(0),
      pl.col("#"),
      pl.col("played").alias("Played"),
      pl.col("fc").alias("FC"),
      pl.col("aj").alias("AJ"),
      pl.col("ajc").alias("AJC"),
      pl.col("overpower").alias("Overpower"),
      pl.col("max_overpower").alias("Max Overpower"),
      pl.col("overpower_percent").alias("Overpower %"),
      pl.col("filtered_max_overpower").alias("Filtered Max Overpower"),
      pl.col("filtered_overpower_percent").alias("Filtered Overpower %"),
    )
  )


overpower_by(combo_df, (pl.col("const").alias("Level") * 2).floor() / 2).sort(
  "Level", descending=True
)

┌───────┬─────┬────────┬─────┬───┬───────────────┬─────────────┬──────────────┬────────────────────┐
│ Level ┆ #   ┆ Played ┆ FC  ┆ … ┆ Max Overpower ┆ Overpower % ┆ Filtered Max ┆ Filtered Overpower │
│       ┆     ┆        ┆     ┆   ┆               ┆             ┆ Overpower    ┆ %                  │
╞═══════╪═════╪════════╪═════╪═══╪═══════════════╪═════════════╪══════════════╪════════════════════╡
│ 15.5  ┆ 22  ┆ 22     ┆ 0   ┆ … ┆ 2042.5        ┆ 88.198      ┆ 2042.5       ┆ 88.198             │
│ 15.0  ┆ 134 ┆ 132    ┆ 1   ┆ … ┆ 12147.5       ┆ 88.873      ┆ 11966.5      ┆ 90.217             │
│ 14.5  ┆ 189 ┆ 189    ┆ 10  ┆ … ┆ 16739.5       ┆ 91.771      ┆ 16739.5      ┆ 91.771             │
│ 14.0  ┆ 308 ┆ 307    ┆ 58  ┆ … ┆ 26470.5       ┆ 93.378      ┆ 26385.0      ┆ 93.68              │
│ 13.5  ┆ 334 ┆ 317    ┆ 79  ┆ … ┆ 27893.0       ┆ 89.414      ┆ 26477.5      ┆ 94.194             │
│ 13.0  ┆ 268 ┆ 218    ┆ 94  ┆ … ┆ 21696.5       ┆ 77.716      ┆ 17639.5      ┆ 95.59              │
│ 12.5  ┆ 294 ┆ 240    ┆ 115 ┆ … ┆ 23066.0       ┆ 78.521      ┆ 18841.5      ┆ 96.127             │
│ 12.0  ┆ 228 ┆ 157    ┆ 140 ┆ … ┆ 17334.0       ┆ 68.058      ┆ 11941.0      ┆ 98.795             │
│ 11.5  ┆ 195 ┆ 141    ┆ 141 ┆ … ┆ 14341.5       ┆ 71.992      ┆ 10378.5      ┆ 99.482             │
│ 11.0  ┆ 155 ┆ 54     ┆ 54  ┆ … ┆ 11008.5       ┆ 34.804      ┆ 3852.0       ┆ 99.464             │
│ 10.5  ┆ 135 ┆ 14     ┆ 11  ┆ … ┆ 9254.5        ┆ 10.107      ┆ 962.0        ┆ 97.234             │
│ 10.0  ┆ 218 ┆ 7      ┆ 6   ┆ … ┆ 14308.5       ┆ 3.212       ┆ 464.5        ┆ 98.956             │
│ 9.5   ┆ 347 ┆ 5      ┆ 5   ┆ … ┆ 21687.5       ┆ 1.434       ┆ 312.5        ┆ 99.53              │
│ 9.0   ┆ 289 ┆ 2      ┆ 2   ┆ … ┆ 17340.0       ┆ 0.688       ┆ 120.0        ┆ 99.475             │
│ 8.5   ┆ 142 ┆ 0      ┆ 0   ┆ … ┆ 8165.0        ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 8.0   ┆ 227 ┆ 0      ┆ 0   ┆ … ┆ 12485.0       ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 7.5   ┆ 90  ┆ 0      ┆ 0   ┆ … ┆ 4725.0        ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 7.0   ┆ 198 ┆ 0      ┆ 0   ┆ … ┆ 9900.0        ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 6.0   ┆ 589 ┆ 0      ┆ 0   ┆ … ┆ 26505.0       ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 5.0   ┆ 551 ┆ 1      ┆ 0   ┆ … ┆ 22040.0       ┆ 0.163       ┆ 40.0         ┆ 90.025             │
│ 4.0   ┆ 289 ┆ 0      ┆ 0   ┆ … ┆ 10115.0       ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 3.0   ┆ 937 ┆ 0      ┆ 0   ┆ … ┆ 28110.0       ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 2.0   ┆ 310 ┆ 0      ┆ 0   ┆ … ┆ 7750.0        ┆ 0.0         ┆ 0.0          ┆ NaN                │
│ 1.0   ┆ 25  ┆ 0      ┆ 0   ┆ … ┆ 500.0         ┆ 0.0         ┆ 0.0          ┆ NaN                │
└───────┴─────┴────────┴─────┴───┴───────────────┴─────────────┴──────────────┴────────────────────┘

In [ ]:
# @title Overpower by Genre

overpower_by(combo_best_difficulty_df, pl.col("genre").alias("Genre"))

┌───────────────┬─────┬────────┬─────┬───┬───────────┬─────────────┬───────────────┬───────────────┐
│ Genre         ┆ #   ┆ Played ┆ FC  ┆ … ┆ Max       ┆ Overpower % ┆ Filtered Max  ┆ Filtered      │
│               ┆     ┆        ┆     ┆   ┆ Overpower ┆             ┆ Overpower     ┆ Overpower %   │
╞═══════════════╪═════╪════════╪═════╪═══╪═══════════╪═════════════╪═══════════════╪═══════════════╡
│ イロドリミド  ┆ 101 ┆ 101    ┆ 45  ┆ … ┆ 8109.5    ┆ 95.713      ┆ 8109.5        ┆ 95.713        │
│ リ            ┆     ┆        ┆     ┆   ┆           ┆             ┆               ┆               │
│ POPS & ANIME  ┆ 240 ┆ 240    ┆ 163 ┆ … ┆ 18711.5   ┆ 97.308      ┆ 18711.5       ┆ 97.308        │
│ VARIETY       ┆ 240 ┆ 240    ┆ 47  ┆ … ┆ 20600.0   ┆ 92.889      ┆ 20600.0       ┆ 92.889        │
│ ORIGINAL      ┆ 394 ┆ 394    ┆ 89  ┆ … ┆ 33426.5   ┆ 93.11       ┆ 33426.5       ┆ 93.11         │
│ niconico      ┆ 303 ┆ 303    ┆ 177 ┆ … ┆ 24215.0   ┆ 96.401      ┆ 24215.0       ┆ 96.401        │
│ 東方Project   ┆ 146 ┆ 146    ┆ 66  ┆ … ┆ 11810.0   ┆ 95.562      ┆ 11810.0       ┆ 95.562        │
│ ゲキマイ      ┆ 173 ┆ 173    ┆ 49  ┆ … ┆ 14555.0   ┆ 94.169      ┆ 14555.0       ┆ 94.169        │
└───────────────┴─────┴────────┴─────┴───┴───────────┴─────────────┴───────────────┴───────────────┘

In [ ]:
# @title Overpower by Version

overpower_by(combo_best_difficulty_df, pl.col("version").alias("Version")).join(
  versions_df, left_on="Version", right_on="version_name", how="left"
).sort("version_number").drop("version_number")

┌────────────────┬─────┬────────┬────┬───┬───────────┬─────────────┬───────────────┬───────────────┐
│ Version        ┆ #   ┆ Played ┆ FC ┆ … ┆ Max       ┆ Overpower % ┆ Filtered Max  ┆ Filtered      │
│                ┆     ┆        ┆    ┆   ┆ Overpower ┆             ┆ Overpower     ┆ Overpower %   │
╞════════════════╪═════╪════════╪════╪═══╪═══════════╪═════════════╪═══════════════╪═══════════════╡
│ CHUNITHM       ┆ 94  ┆ 94     ┆ 32 ┆ … ┆ 7729.0    ┆ 93.513      ┆ 7729.0        ┆ 93.513        │
│ CHUNITHM PLUS  ┆ 47  ┆ 47     ┆ 15 ┆ … ┆ 3882.0    ┆ 93.218      ┆ 3882.0        ┆ 93.218        │
│ AIR            ┆ 78  ┆ 78     ┆ 32 ┆ … ┆ 6356.5    ┆ 94.407      ┆ 6356.5        ┆ 94.407        │
│ AIR PLUS       ┆ 70  ┆ 70     ┆ 31 ┆ … ┆ 5649.5    ┆ 95.221      ┆ 5649.5        ┆ 95.221        │
│ STAR           ┆ 77  ┆ 77     ┆ 33 ┆ … ┆ 6290.5    ┆ 95.085      ┆ 6290.5        ┆ 95.085        │
│ STAR PLUS      ┆ 73  ┆ 73     ┆ 31 ┆ … ┆ 5948.5    ┆ 94.39       ┆ 5948.5        ┆ 94.39         │
│ AMAZON         ┆ 65  ┆ 65     ┆ 25 ┆ … ┆ 5343.0    ┆ 94.743      ┆ 5343.0        ┆ 94.743        │
│ AMAZON PLUS    ┆ 73  ┆ 73     ┆ 28 ┆ … ┆ 5990.5    ┆ 94.837      ┆ 5990.5        ┆ 94.837        │
│ CRYSTAL        ┆ 90  ┆ 90     ┆ 38 ┆ … ┆ 7284.0    ┆ 95.249      ┆ 7284.0        ┆ 95.249        │
│ CRYSTAL PLUS   ┆ 86  ┆ 86     ┆ 38 ┆ … ┆ 6983.5    ┆ 95.256      ┆ 6983.5        ┆ 95.256        │
│ PARADISE       ┆ 59  ┆ 59     ┆ 24 ┆ … ┆ 4882.0    ┆ 94.865      ┆ 4882.0        ┆ 94.865        │
│ PARADISE LOST  ┆ 76  ┆ 76     ┆ 40 ┆ … ┆ 6176.5    ┆ 95.871      ┆ 6176.5        ┆ 95.871        │
│ NEW            ┆ 134 ┆ 134    ┆ 57 ┆ … ┆ 11046.0   ┆ 95.029      ┆ 11046.0       ┆ 95.029        │
│ NEW PLUS       ┆ 93  ┆ 93     ┆ 33 ┆ … ┆ 7613.5    ┆ 94.767      ┆ 7613.5        ┆ 94.767        │
│ SUN            ┆ 115 ┆ 115    ┆ 41 ┆ … ┆ 9502.5    ┆ 94.497      ┆ 9502.5        ┆ 94.497        │
│ SUN PLUS       ┆ 100 ┆ 100    ┆ 34 ┆ … ┆ 8253.0    ┆ 94.316      ┆ 8253.0        ┆ 94.316        │
│ LUMINOUS       ┆ 89  ┆ 89     ┆ 30 ┆ … ┆ 7389.0    ┆ 94.281      ┆ 7389.0        ┆ 94.281        │
│ LUMINOUS PLUS  ┆ 76  ┆ 76     ┆ 25 ┆ … ┆ 6389.5    ┆ 94.505      ┆ 6389.5        ┆ 94.505        │
│ VERSE          ┆ 102 ┆ 102    ┆ 49 ┆ … ┆ 8718.5    ┆ 96.055      ┆ 8718.5        ┆ 96.055        │
└────────────────┴─────┴────────┴────┴───┴───────────┴─────────────┴───────────────┴───────────────┘

# Possession

In [ ]:
# @title Lamps
# @markdown If `cascade` is checked, then AJC will count as AJ+FC and AJ will
# @markdown count as FC. This matches the OP Tracker sheet's lamp table.
cascade = False # @param {"type":"boolean"}


labels = ["Played", "FC", "AJ", "AJC"]
difficulties = pl.DataFrame(
    {
        "difficulty": ["BAS", "ADV", "EXP", "MAS", "ULT"],
    }
)

filters = [
    pl.col("score") > 0,
    pl.col("fc"),
    pl.col("aj"),
    pl.col("ajc"),
]

if not cascade:
    filters[1] &= ~pl.col("aj") & ~pl.col("ajc")
    filters[2] &= ~pl.col("ajc")

pl.concat(
    [
        difficulties.join(
            combo_df.filter(expr).group_by("difficulty").agg(pl.len()), on="difficulty", how="left"
        )
        .fill_null(0)
        .transpose(column_names="difficulty")
        for expr in filters
    ]
).select(
    pl.Series(name="", values=labels),
    pl.col("MAS"),
    pl.col("ULT"),
    (pl.col("MAS") + pl.col("ULT")).alias("Total"),
)

┌────────┬──────┬─────┬───────┐
│        ┆ MAS  ┆ ULT ┆ Total │
╞════════╪══════╪═════╪═══════╡
│ Played ┆ 1597 ┆ 83  ┆ 1680  │
│ FC     ┆ 222  ┆ 10  ┆ 232   │
│ AJ     ┆ 429  ┆ 4   ┆ 433   │
│ AJC    ┆ 2    ┆ 0   ┆ 2     │
└────────┴──────┴─────┴───────┘

In [ ]:
# @title Possession Thresholds
import polars as pl

pos_reqs = [
  ("Silver", 0, "S", 975_000),
  ("Gold", 0.975, "S+", 990_000),
  ("Platinum", 0.99, "SS", 1_000_000),
  ("Rainbow", 0.995, "SSS", 1_007_500),
]

pos_thres_df = pl.from_dicts(
  {
    "pos_name": pos_name,
    "op": max_op * op_pct,
    "rank": rank_name,
    "rank_score": rank_score,
    "rank_left": combo_df.filter(pl.col("difficulty").is_in({"MAS", "ULT"}) & (pl.col("score").fill_null(0) < rank_score)).height,
  }
  for pos_name, op_pct, rank_name, rank_score in pos_reqs
)

pos_done = pos_thres_df.filter((pl.col("op") <= op) & (pl.col("rank_left") == 0))
if pos_done.height == 0:
  print("Possession: None\n")
else:
  print(f"Possession: {pos_done['pos_name'].last()}\n")

pos_thres_df.select(
  pl.col("pos_name").alias("Possession"),
  pl.col("op").alias("OP"),
  (pl.col("op") - op).clip(0).alias("OP Left"),
  pl.col("rank").alias("Rank"),
  pl.col("rank_left").alias("Rank Left"),
)

Possession: None

┌────────────┬─────────────┬───────────┬──────┬───────────┐
│ Possession ┆ OP          ┆ OP Left   ┆ Rank ┆ Rank Left │
╞════════════╪═════════════╪═══════════╪══════╪═══════════╡
│ Silver     ┆ 0.0         ┆ 0.0       ┆ S    ┆ 3         │
│ Gold       ┆ 128141.8125 ┆ 3577.7325 ┆ S+   ┆ 3         │
│ Platinum   ┆ 130113.225  ┆ 5549.145  ┆ SS   ┆ 110       │
│ Rainbow    ┆ 130770.3625 ┆ 6206.2825 ┆ SSS  ┆ 669       │
└────────────┴─────────────┴───────────┴──────┴───────────┘

In [ ]:
# @title Next Possession Missing Charts

rank_missing_df = pos_thres_df.filter(pl.col("rank_left") != 0)
if rank_missing_df.height == 0:
  print("Everything done :)")
  remaining = combo_df.clear()
else:
  remaining = combo_df.filter(pl.col("difficulty").is_in({"MAS", "ULT"})).filter(
    pl.col("score").fill_null(0) < rank_missing_df["rank_score"][0]
  )
  print(f"{remaining.height} charts left for {rank_missing_df['pos_name'][0]} Possession")

3 charts left for Silver Possession

In [ ]:
# @title Missing Charts by Version

remaining.select("version", "id", "difficulty").group_by("version").agg(
  (pl.col("difficulty") == "MAS").sum().alias("mas_left"),
  (pl.col("difficulty") == "ULT").sum().alias("ult_left"),
).join(versions_df, left_on="version", right_on="version_name").sort(
  "version_number"
).select(
  pl.col("version").alias("Version"),
  pl.col("mas_left").fill_null(0).alias("MAS Left"),
  pl.col("ult_left").fill_null(0).alias("ULT Left"),
)

┌─────────┬──────────┬──────────┐
│ Version ┆ MAS Left ┆ ULT Left │
╞═════════╪══════════╪══════════╡
│ AIR     ┆ 0        ┆ 1        │
│ AMAZON  ┆ 0        ┆ 1        │
│ VERSE   ┆ 0        ┆ 1        │
└─────────┴──────────┴──────────┘

In [ ]:
# @title Missing Charts by Genre

remaining.select(pl.col("genre").alias("Genre"), "id", "difficulty").group_by("Genre").agg(
  (pl.col("difficulty") == "MAS").sum().alias("MAS Left"),
  (pl.col("difficulty") == "ULT").sum().alias("ULT Left"),
)

┌──────────────┬──────────┬──────────┐
│ Genre        ┆ MAS Left ┆ ULT Left │
╞══════════════╪══════════╪══════════╡
│ VARIETY      ┆ 0        ┆ 2        │
│ POPS & ANIME ┆ 0        ┆ 1        │
└──────────────┴──────────┴──────────┘

In [ ]:
# @title Missing Charts by Constant
# @markdown Top 50 easiest missing charts
remaining.sort("const").select(
  pl.col("title").alias("Title"),
  pl.col("difficulty").alias("Difficulty"),
  pl.col("const").alias("Constant"),
  pl.col("genre").alias("Genre"),
  pl.col("version").alias("Version"),
).head(50)

┌───────────────┬────────────┬──────────┬──────────────┬─────────┐
│ Title         ┆ Difficulty ┆ Constant ┆ Genre        ┆ Version │
╞═══════════════╪════════════╪══════════╪══════════════╪═════════╡
│ Campus mode!! ┆ ULT        ┆ 14.1     ┆ POPS & ANIME ┆ VERSE   │
│ DataErr0r     ┆ ULT        ┆ 15.1     ┆ VARIETY      ┆ AIR     │
│ Parousia      ┆ ULT        ┆ 15.1     ┆ VARIETY      ┆ AMAZON  │
└───────────────┴────────────┴──────────┴──────────────┴─────────┘

In [ ]:
# @title Possible Overpower Gain
# @markdown Top 50 charts by overpower gain, up to a difficulty
max_const = 14.4 # @param {"type":"number","placeholder":"14.2"}

(
  combo_df.drop("overpower")
  .join(combo_best_difficulty_df.select("id", "overpower"), on="id")
  .with_columns(missing=(pl.col("max_overpower") - (pl.col("overpower") // 10 / 100)))
  .filter(pl.col("missing") > 0)
  .filter(pl.col("const") <= max_const)
  .sort("missing", descending=True)
  .select(
    pl.col("title").alias("Title"),
    pl.col("difficulty").alias("Difficulty"),
    pl.col("const").alias("Constant"),
    pl.col("genre").alias("Genre"),
    pl.col("version").alias("Version"),
    pl.col("overpower").alias("Best Song Overpower") // 10 / 100,
    pl.col("max_overpower").alias("Max Chart Overpower"),
    pl.col("missing").alias("Overpower Gain")
  )
  .head(50)
)

┌────────────┬────────────┬──────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ Title      ┆ Difficulty ┆ Constant ┆ Genre      ┆ Version    ┆ Best Song ┆ Max Chart ┆ Overpower │
│            ┆            ┆          ┆            ┆            ┆ Overpower ┆ Overpower ┆ Gain      │
╞════════════╪════════════╪══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ オススメ☆♂ ┆ MAS        ┆ 14.4     ┆ ORIGINAL   ┆ AIR PLUS   ┆ 77.07     ┆ 87.0      ┆ 9.93      │
│ ♀☆でぃすと ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ぴあ       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ きゅうりバ ┆ MAS        ┆ 14.3     ┆ 東方Projec ┆ STAR PLUS  ┆ 76.59     ┆ 86.5      ┆ 9.91      │
│ ーにダイブ ┆            ┆          ┆ t          ┆            ┆           ┆           ┆           │
│ 音弾超人ゴ ┆ MAS        ┆ 13.9     ┆ VARIETY    ┆ CRYSTAL    ┆ 74.7      ┆ 84.5      ┆ 9.8       │
│ リライザー ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ SILENT     ┆ MAS        ┆ 14.2     ┆ ゲキマイ   ┆ LUMINOUS   ┆ 76.24     ┆ 86.0      ┆ 9.76      │
│ BLUE       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Jack-the-R ┆ MAS        ┆ 14.2     ┆ VARIETY    ┆ CHUNITHM   ┆ 76.25     ┆ 86.0      ┆ 9.75      │
│ ipper◆     ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ 任せてJC陰 ┆ MAS        ┆ 13.3     ┆ ORIGINAL   ┆ SUN        ┆ 71.77     ┆ 81.5      ┆ 9.73      │
│ 陽師☆八雲  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ちゃん     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Alice's    ┆ MAS        ┆ 13.3     ┆ VARIETY    ┆ SUN        ┆ 71.78     ┆ 81.5      ┆ 9.72      │
│ Suitcase   ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Iudicium   ┆ MAS        ┆ 14.4     ┆ ゲキマイ   ┆ NEW        ┆ 77.31     ┆ 87.0      ┆ 9.69      │
│ “Apocalyps ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ is Mix”    ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ GEMINI -C- ┆ MAS        ┆ 14.2     ┆ ORIGINAL   ┆ CHUNITHM   ┆ 76.36     ┆ 86.0      ┆ 9.64      │
│            ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ felys      ┆ MAS        ┆ 14.4     ┆ VARIETY    ┆ CRYSTAL    ┆ 77.39     ┆ 87.0      ┆ 9.61      │
│ -final     ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ remix-     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ラブって♡  ┆ MAS        ┆ 13.3     ┆ POPS &     ┆ STAR PLUS  ┆ 72.0      ┆ 81.5      ┆ 9.5       │
│ ジュエリー ┆            ┆          ┆ ANIME      ┆            ┆           ┆           ┆           │
│ ♪えんじぇ  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ る☆ブレイ  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ク！！     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Her        ┆ MAS        ┆ 13.5     ┆ VARIETY    ┆ AIR        ┆ 73.03     ┆ 82.5      ┆ 9.47      │
│ Majesty    ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ BlazinG    ┆ MAS        ┆ 14.3     ┆ ORIGINAL   ┆ STAR PLUS  ┆ 77.04     ┆ 86.5      ┆ 9.46      │
│ AIR        ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ The wheel  ┆ MAS        ┆ 14.4     ┆ ORIGINAL   ┆ CHUNITHM   ┆ 77.55     ┆ 87.0      ┆ 9.45      │
│ to the     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ right      ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Super      ┆ MAS        ┆ 14.3     ┆ VARIETY    ┆ AMAZON     ┆ 77.06     ┆ 86.5      ┆ 9.44      │
│ Lovely     ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ (Heavenly  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Remix)     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 狩猟戦旗～ ┆ MAS        ┆ 14.2     ┆ POPS &     ┆ CRYSTAL    ┆ 76.63     ┆ 86.0      ┆ 9.37      │
│ REQUIEM    ┆            ┆          ┆ ANIME      ┆ PLUS       ┆           ┆           ┆           │
│ 異星にいこ ┆ MAS        ┆ 13.2     ┆ niconico   ┆ SUN PLUS   ┆ 71.65     ┆ 81.0      ┆ 9.35      │
│ うね       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Sakura     ┆ MAS        ┆ 13.3     ┆ VARIETY    ┆ AIR        ┆ 72.17     ┆ 81.5      ┆ 9.33      │
│ Fubuki     ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Elusive    ┆ MAS        ┆ 14.3     ┆ ORIGINAL   ┆ LUMINOUS   ┆ 77.21     ┆ 86.5      ┆ 9.29      │
│ Enforcer   ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ エキセント ┆ MAS        ┆ 13.7     ┆ ORIGINAL   ┆ CRYSTAL    ┆ 74.25     ┆ 83.5      ┆ 9.25      │
│ リックコン ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ コン       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Alma       ┆ MAS        ┆ 14.0     ┆ ORIGINAL   ┆ CHUNITHM   ┆ 75.77     ┆ 85.0      ┆ 9.23      │
│ MELtin' 17 ┆ MAS        ┆ 14.0     ┆ イロドリミ ┆ PARADISE   ┆ 75.77     ┆ 85.0      ┆ 9.23      │
│            ┆            ┆          ┆ ドリ       ┆            ┆           ┆           ┆           │
│ TRUST      ┆ MAS        ┆ 13.1     ┆ イロドリミ ┆ AIR PLUS   ┆ 71.28     ┆ 80.5      ┆ 9.22      │
│            ┆            ┆          ┆ ドリ       ┆            ┆           ┆           ┆           │
│ First      ┆ MAS        ┆ 13.7     ┆ ORIGINAL   ┆ LUMINOUS   ┆ 74.29     ┆ 83.5      ┆ 9.21      │
│ Light      ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ KILLER B   ┆ MAS        ┆ 13.7     ┆ niconico   ┆ CRYSTAL    ┆ 74.3      ┆ 83.5      ┆ 9.2       │
│            ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ 痛快リズム ┆ MAS        ┆ 14.2     ┆ イロドリミ ┆ SUN        ┆ 76.82     ┆ 86.0      ┆ 9.18      │
│ アクション ┆            ┆          ┆ ドリ       ┆            ┆           ┆           ┆           │
│ 「B.B.K.K. ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ B.K.K.」   ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ のぼれ！す ┆ MAS        ┆ 14.3     ┆ niconico   ┆ STAR       ┆ 77.34     ┆ 86.5      ┆ 9.16      │
│ すめ！高い ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 塔         ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ハイセンス ┆ MAS        ┆ 14.4     ┆ niconico   ┆ AMAZON     ┆ 77.88     ┆ 87.0      ┆ 9.12      │
│ ナンセンス ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ アナタニナ ┆ MAS        ┆ 13.4     ┆ ORIGINAL   ┆ NEW PLUS   ┆ 72.9      ┆ 82.0      ┆ 9.1       │
│ ルノ       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ シャッキー ┆ MAS        ┆ 14.4     ┆ ORIGINAL   ┆ CRYSTAL    ┆ 77.98     ┆ 87.0      ┆ 9.02      │
│ ーン！！   ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ 最終鬼畜妹 ┆ MAS        ┆ 14.0     ┆ 東方Projec ┆ CHUNITHM   ┆ 75.99     ┆ 85.0      ┆ 9.01      │
│ ・一部声   ┆            ┆          ┆ t          ┆            ┆           ┆           ┆           │
│ 札付きのワ ┆ MAS        ┆ 13.6     ┆ ORIGINAL   ┆ AIR PLUS   ┆ 73.99     ┆ 83.0      ┆ 9.01      │
│ ル　～マイ ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ケルのうた ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ～         ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Realize    ┆ MAS        ┆ 13.3     ┆ POPS &     ┆ NEW        ┆ 72.5      ┆ 81.5      ┆ 9.0       │
│            ┆            ┆          ┆ ANIME      ┆            ┆           ┆           ┆           │
│ SKYSCRAPER ┆ MAS        ┆ 13.9     ┆ VARIETY    ┆ PARADISE   ┆ 75.51     ┆ 84.5      ┆ 8.99      │
│ XL TECHNO  ┆ MAS        ┆ 13.6     ┆ VARIETY    ┆ CHUNITHM   ┆ 74.04     ┆ 83.0      ┆ 8.96      │
│            ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ チョウの標 ┆ MAS        ┆ 14.3     ┆ VARIETY    ┆ CRYSTAL    ┆ 77.54     ┆ 86.5      ┆ 8.96      │
│ 本         ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ コモリの怪 ┆ MAS        ┆ 14.1     ┆ ORIGINAL   ┆ AMAZON     ┆ 76.55     ┆ 85.5      ┆ 8.95      │
│ 物         ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ Vibrant    ┆ MAS        ┆ 14.1     ┆ ORIGINAL   ┆ AMAZON     ┆ 76.57     ┆ 85.5      ┆ 8.93      │
│ Verve      ┆            ┆          ┆            ┆ PLUS       ┆           ┆           ┆           │
│ stella=ste ┆ MAS        ┆ 13.7     ┆ ORIGINAL   ┆ CHUNITHM   ┆ 74.58     ┆ 83.5      ┆ 8.92      │
│ LLa        ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 僕らのFree ┆ MAS        ┆ 14.1     ┆ イロドリミ ┆ NEW PLUS   ┆ 76.6      ┆ 85.5      ┆ 8.9       │
│ dom DiVE↓  ┆            ┆          ┆ ドリ       ┆            ┆           ┆           ┆           │
│ ギガンティ ┆ MAS        ┆ 14.1     ┆ niconico   ┆ CHUNITHM   ┆ 76.62     ┆ 85.5      ┆ 8.88      │
│ ックO.T.N  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ハートアタ ┆ MAS        ┆ 14.4     ┆ ORIGINAL   ┆ AMAZON     ┆ 78.13     ┆ 87.0      ┆ 8.87      │
│ ック       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 言ノ葉カル ┆ ULT        ┆ 14.3     ┆ ゲキマイ   ┆ CHUNITHM   ┆ 77.64     ┆ 86.5      ┆ 8.86      │
│ マ         ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ サンシャイ ┆ MAS        ┆ 13.9     ┆ ORIGINAL   ┆ STAR PLUS  ┆ 75.64     ┆ 84.5      ┆ 8.86      │
│ ンサマー☆  ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 夏期講習   ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ ロウワー   ┆ MAS        ┆ 13.7     ┆ niconico   ┆ LUMINOUS   ┆ 74.64     ┆ 83.5      ┆ 8.86      │
│ Ignition   ┆ MAS        ┆ 13.8     ┆ ORIGINAL   ┆ SUN        ┆ 75.18     ┆ 84.0      ┆ 8.82      │
│ STAR       ┆ MAS        ┆ 13.5     ┆ ORIGINAL   ┆ CHUNITHM   ┆ 73.69     ┆ 82.5      ┆ 8.81      │
│ 凛として咲 ┆ ULT        ┆ 14.3     ┆ VARIETY    ┆ AIR        ┆ 77.71     ┆ 86.5      ┆ 8.79      │
│ く花の如く ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
│ 幻想のサテ ┆ MAS        ┆ 14.2     ┆ 東方Projec ┆ AIR        ┆ 77.22     ┆ 86.0      ┆ 8.78      │
│ ライト     ┆            ┆          ┆ t          ┆            ┆           ┆           ┆           │
│ ベースライ ┆ MAS        ┆ 14.2     ┆ VARIETY    ┆ PARADISE   ┆ 77.24     ┆ 86.0      ┆ 8.76      │
│ ンやってる ┆            ┆          ┆            ┆ LOST       ┆           ┆           ┆           │
│ ？笑       ┆            ┆          ┆            ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
# @title Almost All Justice
# @markdown Top 50 MAS/ULT charts by difficulty, with lowest attack+miss between
# @markdown 1 and `threshold`
# @markdown
# @markdown Note that these may not be your highest scores on these charts

# make sure all the notes were actually played
full_played = track_list_filtered.join(scores_df, on=["id", "difficulty"]).filter(
  pl.col("notes") == pl.sum_horizontal("jcrit", "justice", "attack", "miss"),
  pl.col("difficulty").is_in({"MAS", "ULT"}),
)

threshold = 1 # @param {"type":"integer","placeholder":"1"}

almost_aj = full_played.with_columns(mistakes=pl.sum_horizontal("attack", "miss")).group_by("id", "difficulty").agg(
  pl.first("title", "artist", "genre", "version", "const"),
  pl.col("score", "jcrit", "justice", "attack", "miss", "mistakes").sort_by("mistakes", "miss").first(),
).filter(pl.col("mistakes").is_between(1, threshold)).sort("const").select(
  Title="title",
  Difficulty="difficulty",
  Constant="const",
  Genre="genre",
  Version="version",
  Score="score",
  JC="jcrit",
  J="justice",
  A="attack",
  M="miss",
)

print(f"{almost_aj.height} total")
almost_aj.head(50)

117 total

┌─────────────────────────────────┬────────────┬──────────┬────────────────┬───┬──────┬────┬───┬───┐
│ Title                           ┆ Difficulty ┆ Constant ┆ Genre          ┆ … ┆ JC   ┆ J  ┆ A ┆ M │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╪═══╪══════╪════╪═══╪═══╡
│ 超常マイマイン                  ┆ MAS        ┆ 12.0     ┆ ゲキマイ       ┆ … ┆ 1987 ┆ 19 ┆ 0 ┆ 1 │
│ どこにもいかない                ┆ MAS        ┆ 12.0     ┆ イロドリミドリ ┆ … ┆ 1267 ┆ 18 ┆ 1 ┆ 0 │
│ Black'n White JAMMIN' CATS      ┆ MAS        ┆ 12.2     ┆ イロドリミドリ ┆ … ┆ 1519 ┆ 13 ┆ 0 ┆ 1 │
│ ハート・ビート                  ┆ MAS        ┆ 12.2     ┆ イロドリミドリ ┆ … ┆ 1395 ┆ 29 ┆ 0 ┆ 1 │
│ このふざけた素晴らしき世界は、  ┆ MAS        ┆ 12.2     ┆ niconico       ┆ … ┆ 1632 ┆ 24 ┆ 0 ┆ 1 │
│ 僕の為にある                    ┆            ┆          ┆                ┆   ┆      ┆    ┆   ┆   │
│ BURST THE GRAVITY               ┆ MAS        ┆ 12.3     ┆ POPS & ANIME   ┆ … ┆ 1499 ┆ 8  ┆ 0 ┆ 1 │
│ 帝国少女                        ┆ MAS        ┆ 12.3     ┆ niconico       ┆ … ┆ 1386 ┆ 17 ┆ 1 ┆ 0 │
│ 目覚めRETURNER                  ┆ MAS        ┆ 12.3     ┆ POPS & ANIME   ┆ … ┆ 1440 ┆ 8  ┆ 1 ┆ 0 │
│ テリトリーバトル                ┆ MAS        ┆ 12.4     ┆ ORIGINAL       ┆ … ┆ 1438 ┆ 10 ┆ 0 ┆ 1 │
│ 僕の戦争                        ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 2203 ┆ 20 ┆ 0 ┆ 1 │
│ 美少女無罪♡パイレーツ           ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 1925 ┆ 7  ┆ 0 ┆ 1 │
│ うまぴょい伝説                  ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 2018 ┆ 58 ┆ 1 ┆ 0 │
│ 凛として咲く花の如く            ┆ MAS        ┆ 12.5     ┆ VARIETY        ┆ … ┆ 1306 ┆ 20 ┆ 1 ┆ 0 │
│ 拝啓、桜舞い散るこの日に        ┆ MAS        ┆ 12.5     ┆ niconico       ┆ … ┆ 1522 ┆ 16 ┆ 0 ┆ 1 │
│ 悪戯                            ┆ MAS        ┆ 12.5     ┆ ゲキマイ       ┆ … ┆ 1357 ┆ 11 ┆ 1 ┆ 0 │
│ elegante                        ┆ MAS        ┆ 12.5     ┆ VARIETY        ┆ … ┆ 965  ┆ 34 ┆ 1 ┆ 0 │
│ 夏宵スターマイン                ┆ MAS        ┆ 12.5     ┆ ゲキマイ       ┆ … ┆ 1548 ┆ 6  ┆ 1 ┆ 0 │
│ 怪物                            ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 1996 ┆ 11 ┆ 1 ┆ 0 │
│ 涙色メモリア                    ┆ MAS        ┆ 12.6     ┆ ORIGINAL       ┆ … ┆ 1740 ┆ 14 ┆ 1 ┆ 0 │
│ Flower                          ┆ MAS        ┆ 12.6     ┆ ゲキマイ       ┆ … ┆ 1892 ┆ 9  ┆ 0 ┆ 1 │
│ 青春コンプレックス              ┆ MAS        ┆ 12.6     ┆ POPS & ANIME   ┆ … ┆ 1628 ┆ 40 ┆ 1 ┆ 0 │
│ テレキャスタービーボーイ        ┆ MAS        ┆ 12.6     ┆ niconico       ┆ … ┆ 1452 ┆ 12 ┆ 1 ┆ 0 │
│ シル・ヴ・プレジデント          ┆ MAS        ┆ 12.6     ┆ POPS & ANIME   ┆ … ┆ 1731 ┆ 11 ┆ 1 ┆ 0 │
│ 不可解                          ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1673 ┆ 33 ┆ 1 ┆ 0 │
│ クレイジー・ビート              ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 1608 ┆ 20 ┆ 0 ┆ 1 │
│ ＊ハロー、プラネット。          ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 1871 ┆ 14 ┆ 1 ┆ 0 │
│ マツケンサンバⅡ                 ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1351 ┆ 30 ┆ 1 ┆ 0 │
│ あの世行きのバスに乗ってさらば  ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 1211 ┆ 16 ┆ 0 ┆ 1 │
│ 。                              ┆            ┆          ┆                ┆   ┆      ┆    ┆   ┆   │
│ Glory Steady Go!                ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 809  ┆ 10 ┆ 1 ┆ 0 │
│ メイドと血の懐中時計            ┆ MAS        ┆ 12.7     ┆ 東方Project    ┆ … ┆ 1717 ┆ 5  ┆ 1 ┆ 0 │
│ なにやってもうまくいかない      ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1270 ┆ 18 ┆ 0 ┆ 1 │
│ 砂の惑星 feat. HATSUNE MIKU     ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1396 ┆ 18 ┆ 1 ┆ 0 │
│ 卑怯戦隊うろたんだー            ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1559 ┆ 22 ┆ 1 ┆ 0 │
│ 甲賀忍法帖                      ┆ MAS        ┆ 12.8     ┆ POPS & ANIME   ┆ … ┆ 1602 ┆ 23 ┆ 0 ┆ 1 │
│ Cosmic Magic Shooter            ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1192 ┆ 16 ┆ 0 ┆ 1 │
│ 愛されなくても君がいる          ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1723 ┆ 15 ┆ 1 ┆ 0 │
│ トゥッティ！                    ┆ MAS        ┆ 12.8     ┆ POPS & ANIME   ┆ … ┆ 2027 ┆ 18 ┆ 1 ┆ 0 │
│ 永遠のメロディ                  ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1423 ┆ 16 ┆ 0 ┆ 1 │
│ FLOATED CALM                    ┆ MAS        ┆ 12.8     ┆ VARIETY        ┆ … ┆ 1626 ┆ 14 ┆ 1 ┆ 0 │
│ 心予報                          ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1599 ┆ 7  ┆ 0 ┆ 1 │
│ キラメキライダー☆               ┆ MAS        ┆ 12.8     ┆ POPS & ANIME   ┆ … ┆ 1814 ┆ 15 ┆ 1 ┆ 0 │
│ つるぺったん                    ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1779 ┆ 6  ┆ 1 ┆ 0 │
│ Road without Road               ┆ MAS        ┆ 12.8     ┆ イロドリミドリ ┆ … ┆ 1830 ┆ 17 ┆ 1 ┆ 0 │
│ STAR IN THE WORLD               ┆ MAS        ┆ 12.8     ┆ ORIGINAL       ┆ … ┆ 1877 ┆ 13 ┆ 1 ┆ 0 │
│ Dive a Wave                     ┆ MAS        ┆ 12.9     ┆ ORIGINAL       ┆ … ┆ 1271 ┆ 26 ┆ 1 ┆ 0 │
│ Sweet Devil                     ┆ MAS        ┆ 12.9     ┆ niconico       ┆ … ┆ 1094 ┆ 41 ┆ 1 ┆ 0 │
│ ロスタイムメモリー              ┆ MAS        ┆ 12.9     ┆ niconico       ┆ … ┆ 1603 ┆ 17 ┆ 0 ┆ 1 │
│ 青春サイダー                    ┆ MAS        ┆ 12.9     ┆ POPS & ANIME   ┆ … ┆ 1690 ┆ 7  ┆ 0 ┆ 1 │
│ ヒバリ                          ┆ MAS        ┆ 12.9     ┆ POPS & ANIME   ┆ … ┆ 1295 ┆ 13 ┆ 1 ┆ 0 │
│ Scream out! -CHUNITHM Tuning-   ┆ MAS        ┆ 12.9     ┆ 東方Project    ┆ … ┆ 1746 ┆ 23 ┆ 1 ┆ 0 │
└─────────────────────────────────┴────────────┴──────────┴────────────────┴───┴──────┴────┴───┴───┘

In [ ]:
# @title Almost Full Combo
# @markdown Top 50 MAS/ULT charts by difficulty, with lowest miss between 1 and
# @markdown `threshold`

threshold = 1 # @param {"type":"integer","placeholder":"1"}

almost_fc = full_played.group_by("id", "difficulty").agg(
  pl.first("title", "artist", "genre", "version", "const"),
  pl.col("score", "jcrit", "justice", "attack", "miss").sort_by("miss").first(),
).filter(pl.col("miss").is_between(1, threshold)).sort("const").select(
  Title="title",
  Difficulty="difficulty",
  Constant="const",
  Genre="genre",
  Version="version",
  Score="score",
  JC="jcrit",
  J="justice",
  A="attack",
  M="miss",
)

print(f"{almost_fc.height} total")
almost_fc.head(50)

253 total

┌────────────────────────────────┬────────────┬──────────┬────────────────┬───┬──────┬────┬────┬───┐
│ Title                          ┆ Difficulty ┆ Constant ┆ Genre          ┆ … ┆ JC   ┆ J  ┆ A  ┆ M │
╞════════════════════════════════╪════════════╪══════════╪════════════════╪═══╪══════╪════╪════╪═══╡
│ Theme of SeelischTact          ┆ MAS        ┆ 12.0     ┆ ORIGINAL       ┆ … ┆ 1221 ┆ 15 ┆ 1  ┆ 1 │
│ 神曲                           ┆ MAS        ┆ 12.0     ┆ niconico       ┆ … ┆ 1541 ┆ 12 ┆ 2  ┆ 1 │
│ 響                             ┆ MAS        ┆ 12.0     ┆ ORIGINAL       ┆ … ┆ 2455 ┆ 39 ┆ 5  ┆ 1 │
│ 超常マイマイン                 ┆ MAS        ┆ 12.0     ┆ ゲキマイ       ┆ … ┆ 1986 ┆ 17 ┆ 3  ┆ 1 │
│ FEEL the BEATS                 ┆ MAS        ┆ 12.1     ┆ ゲキマイ       ┆ … ┆ 1485 ┆ 11 ┆ 3  ┆ 1 │
│ Barbed Eye                     ┆ MAS        ┆ 12.1     ┆ ゲキマイ       ┆ … ┆ 1751 ┆ 21 ┆ 4  ┆ 1 │
│ brilliant better               ┆ MAS        ┆ 12.1     ┆ イロドリミドリ ┆ … ┆ 1508 ┆ 20 ┆ 2  ┆ 1 │
│ ハート・ビート                 ┆ MAS        ┆ 12.2     ┆ イロドリミドリ ┆ … ┆ 1395 ┆ 27 ┆ 2  ┆ 1 │
│ ハッピーエンドをはじめから     ┆ MAS        ┆ 12.2     ┆ POPS & ANIME   ┆ … ┆ 1860 ┆ 18 ┆ 2  ┆ 1 │
│ Counselor                      ┆ MAS        ┆ 12.3     ┆ ORIGINAL       ┆ … ┆ 1241 ┆ 16 ┆ 1  ┆ 1 │
│ BURST THE GRAVITY              ┆ MAS        ┆ 12.3     ┆ POPS & ANIME   ┆ … ┆ 1480 ┆ 25 ┆ 2  ┆ 1 │
│ JET                            ┆ MAS        ┆ 12.3     ┆ VARIETY        ┆ … ┆ 1413 ┆ 42 ┆ 2  ┆ 1 │
│ オン×ステージ！                ┆ MAS        ┆ 12.3     ┆ ゲキマイ       ┆ … ┆ 1979 ┆ 15 ┆ 5  ┆ 1 │
│ テリトリーバトル               ┆ MAS        ┆ 12.4     ┆ ORIGINAL       ┆ … ┆ 1438 ┆ 10 ┆ 0  ┆ 1 │
│ 僕の戦争                       ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 2203 ┆ 20 ┆ 0  ┆ 1 │
│ ネトゲ廃人シュプレヒコール     ┆ MAS        ┆ 12.5     ┆ niconico       ┆ … ┆ 1531 ┆ 13 ┆ 5  ┆ 1 │
│ イカサマライフゲイム           ┆ MAS        ┆ 12.5     ┆ niconico       ┆ … ┆ 1664 ┆ 32 ┆ 1  ┆ 1 │
│ 美少女無罪♡パイレーツ          ┆ MAS        ┆ 12.5     ┆ POPS & ANIME   ┆ … ┆ 1925 ┆ 7  ┆ 0  ┆ 1 │
│ 拝啓、桜舞い散るこの日に       ┆ MAS        ┆ 12.5     ┆ niconico       ┆ … ┆ 1522 ┆ 16 ┆ 0  ┆ 1 │
│ 哀しみ集め                     ┆ MAS        ┆ 12.5     ┆ ORIGINAL       ┆ … ┆ 1516 ┆ 20 ┆ 4  ┆ 1 │
│ Forever and…                   ┆ MAS        ┆ 12.5     ┆ イロドリミドリ ┆ … ┆ 1493 ┆ 15 ┆ 2  ┆ 1 │
│ コトバウタ                     ┆ MAS        ┆ 12.5     ┆ イロドリミドリ ┆ … ┆ 1512 ┆ 9  ┆ 2  ┆ 1 │
│ 愛き夜道 feat.                 ┆ MAS        ┆ 12.5     ┆ 東方Project    ┆ … ┆ 1100 ┆ 25 ┆ 2  ┆ 1 │
│ ランコ、雨天決行               ┆            ┆          ┆                ┆   ┆      ┆    ┆    ┆   │
│ WE GOTTA SOUL                  ┆ MAS        ┆ 12.5     ┆ ORIGINAL       ┆ … ┆ 1533 ┆ 26 ┆ 1  ┆ 1 │
│ スン(マイル)フラワー～Sun(Mile ┆ MAS        ┆ 12.5     ┆ ゲキマイ       ┆ … ┆ 2227 ┆ 36 ┆ 1  ┆ 1 │
│ )Flower                        ┆            ┆          ┆                ┆   ┆      ┆    ┆    ┆   │
│ 呪歌-JyuKa-                    ┆ MAS        ┆ 12.5     ┆ ORIGINAL       ┆ … ┆ 1513 ┆ 54 ┆ 7  ┆ 1 │
│ Ghost Dance                    ┆ MAS        ┆ 12.5     ┆ ORIGINAL       ┆ … ┆ 1501 ┆ 5  ┆ 2  ┆ 1 │
│ Flower                         ┆ MAS        ┆ 12.6     ┆ ゲキマイ       ┆ … ┆ 1892 ┆ 9  ┆ 0  ┆ 1 │
│ 君と、この瞬間                 ┆ MAS        ┆ 12.6     ┆ イロドリミドリ ┆ … ┆ 1988 ┆ 32 ┆ 2  ┆ 1 │
│ 千本桜                         ┆ MAS        ┆ 12.6     ┆ niconico       ┆ … ┆ 1334 ┆ 27 ┆ 5  ┆ 1 │
│ ALL I WANNA DO                 ┆ MAS        ┆ 12.6     ┆ イロドリミドリ ┆ … ┆ 1755 ┆ 33 ┆ 11 ┆ 1 │
│ Help me, ERINNNNNN!! -Cranky   ┆ MAS        ┆ 12.6     ┆ 東方Project    ┆ … ┆ 1183 ┆ 29 ┆ 3  ┆ 1 │
│ r…                             ┆            ┆          ┆                ┆   ┆      ┆    ┆    ┆   │
│ アスノヨゾラ哨戒班             ┆ MAS        ┆ 12.6     ┆ niconico       ┆ … ┆ 1591 ┆ 32 ┆ 7  ┆ 1 │
│ 迷星叫                         ┆ MAS        ┆ 12.6     ┆ POPS & ANIME   ┆ … ┆ 1723 ┆ 25 ┆ 2  ┆ 1 │
│ Perfect Shining!!              ┆ MAS        ┆ 12.7     ┆ ゲキマイ       ┆ … ┆ 1814 ┆ 35 ┆ 7  ┆ 1 │
│ あの世行きのバスに乗ってさらば ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 1211 ┆ 16 ┆ 0  ┆ 1 │
│ 。                             ┆            ┆          ┆                ┆   ┆      ┆    ┆    ┆   │
│ 俺ら東京さ行ぐだ               ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1801 ┆ 32 ┆ 3  ┆ 1 │
│ "STAR"T                        ┆ MAS        ┆ 12.7     ┆ イロドリミドリ ┆ … ┆ 1986 ┆ 19 ┆ 1  ┆ 1 │
│ クレイジー・ビート             ┆ MAS        ┆ 12.7     ┆ niconico       ┆ … ┆ 1608 ┆ 20 ┆ 0  ┆ 1 │
│ さんさーら！                   ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1839 ┆ 20 ┆ 1  ┆ 1 │
│ なにやってもうまくいかない     ┆ MAS        ┆ 12.7     ┆ POPS & ANIME   ┆ … ┆ 1270 ┆ 18 ┆ 0  ┆ 1 │
│ リハーサルタイム               ┆ MAS        ┆ 12.7     ┆ イロドリミドリ ┆ … ┆ 1612 ┆ 18 ┆ 1  ┆ 1 │
│ What color...                  ┆ MAS        ┆ 12.7     ┆ ゲキマイ       ┆ … ┆ 1838 ┆ 29 ┆ 3  ┆ 1 │
│ 放課後革命                     ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1916 ┆ 33 ┆ 3  ┆ 1 │
│ WARNING×WARNING×WARNING        ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1935 ┆ 32 ┆ 4  ┆ 1 │
│ 寝起きヤシの木                 ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1160 ┆ 19 ┆ 4  ┆ 1 │
│ 禁じられた遊び                 ┆ MAS        ┆ 12.8     ┆ POPS & ANIME   ┆ … ┆ 1556 ┆ 11 ┆ 3  ┆ 1 │
│ No Routine                     ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1677 ┆ 30 ┆ 7  ┆ 1 │
│ 骸骨楽団とリリア               ┆ MAS        ┆ 12.8     ┆ niconico       ┆ … ┆ 1435 ┆ 19 ┆ 1  ┆ 1 │
│ Cosmic Magic Shooter           ┆ MAS        ┆ 12.8     ┆ 東方Project    ┆ … ┆ 1192 ┆ 16 ┆ 0  ┆ 1 │
└────────────────────────────────┴────────────┴──────────┴────────────────┴───┴──────┴────┴────┴───┘

In [ ]:
# @title Almost All Justice Critical
# @markdown Top 50 MAS/ULT charts by difficulty, with lowest justice+attack+miss
# @markdown between 1 and `threshold`

threshold = 3 # @param {"type":"integer","placeholder":"1"}

almost_ajc = full_played.with_columns(mistakes=pl.sum_horizontal("justice", "attack", "miss")).group_by("id", "difficulty").agg(
  pl.first("title", "artist", "genre", "version", "const"),
  pl.col("score", "jcrit", "justice", "attack", "miss", "mistakes").sort_by("mistakes", "miss", "attack", "justice").first(),
).filter(pl.col("mistakes").is_between(1, threshold)).sort("const").select(
  Title="title",
  Difficulty="difficulty",
  Constant="const",
  Genre="genre",
  Version="version",
  Score="score",
  JC="jcrit",
  J="justice",
  A="attack",
  M="miss",
)

print(f"{almost_ajc.height} total")
almost_ajc.head(50)

21 total

┌─────────────────────────────────┬────────────┬──────────┬──────────────┬───┬──────┬───┬───┬───┐
│ Title                           ┆ Difficulty ┆ Constant ┆ Genre        ┆ … ┆ JC   ┆ J ┆ A ┆ M │
╞═════════════════════════════════╪════════════╪══════════╪══════════════╪═══╪══════╪═══╪═══╪═══╡
│ 輪舞-revolution                 ┆ MAS        ┆ 10.7     ┆ POPS & ANIME ┆ … ┆ 1252 ┆ 2 ┆ 0 ┆ 0 │
│ 歩いていこう！                  ┆ MAS        ┆ 11.2     ┆ POPS & ANIME ┆ … ┆ 1265 ┆ 1 ┆ 0 ┆ 0 │
│ かっとばせ！未来へ              ┆ MAS        ┆ 11.4     ┆ POPS & ANIME ┆ … ┆ 2014 ┆ 3 ┆ 0 ┆ 0 │
│ FRIDAY FRIDAY                   ┆ MAS        ┆ 11.4     ┆ ORIGINAL     ┆ … ┆ 1333 ┆ 2 ┆ 0 ┆ 0 │
│ Ring                            ┆ MAS        ┆ 11.5     ┆ ORIGINAL     ┆ … ┆ 1310 ┆ 3 ┆ 0 ┆ 0 │
│ magnet                          ┆ MAS        ┆ 11.5     ┆ niconico     ┆ … ┆ 1191 ┆ 2 ┆ 0 ┆ 0 │
│ みくみくにしてあげる♪【してやん ┆ MAS        ┆ 11.5     ┆ niconico     ┆ … ┆ 1137 ┆ 2 ┆ 0 ┆ 0 │
│ よ】                            ┆            ┆          ┆              ┆   ┆      ┆   ┆   ┆   │
│ どうぶつ☆パラダイス             ┆ MAS        ┆ 11.5     ┆ ゲキマイ     ┆ … ┆ 1803 ┆ 3 ┆ 0 ┆ 0 │
│ ヒトリシズカ(Arranged: Iceon)   ┆ MAS        ┆ 11.9     ┆ 東方Project  ┆ … ┆ 834  ┆ 2 ┆ 0 ┆ 0 │
│ 君のせい                        ┆ MAS        ┆ 11.9     ┆ POPS & ANIME ┆ … ┆ 1700 ┆ 3 ┆ 0 ┆ 0 │
│ 未来への咆哮                    ┆ MAS        ┆ 11.9     ┆ POPS & ANIME ┆ … ┆ 1470 ┆ 2 ┆ 0 ┆ 0 │
│ とまどい→レシピ                 ┆ MAS        ┆ 11.9     ┆ POPS & ANIME ┆ … ┆ 1612 ┆ 1 ┆ 0 ┆ 0 │
│ 前前前世                        ┆ MAS        ┆ 12.0     ┆ POPS & ANIME ┆ … ┆ 1406 ┆ 2 ┆ 0 ┆ 0 │
│ Catch the Wave                  ┆ MAS        ┆ 12.1     ┆ niconico     ┆ … ┆ 1538 ┆ 1 ┆ 0 ┆ 0 │
│ 壊れた人形のマーチ              ┆ MAS        ┆ 12.2     ┆ 東方Project  ┆ … ┆ 1675 ┆ 1 ┆ 0 ┆ 0 │
│ ReCoda                          ┆ MAS        ┆ 12.3     ┆ POPS & ANIME ┆ … ┆ 1098 ┆ 3 ┆ 0 ┆ 0 │
│ 放課後ストライド                ┆ MAS        ┆ 12.3     ┆ niconico     ┆ … ┆ 1754 ┆ 2 ┆ 0 ┆ 0 │
│ ハッピータイフーン              ┆ MAS        ┆ 12.4     ┆ POPS & ANIME ┆ … ┆ 1532 ┆ 1 ┆ 0 ┆ 0 │
│ インフェルノ                    ┆ MAS        ┆ 12.4     ┆ POPS & ANIME ┆ … ┆ 1654 ┆ 2 ┆ 0 ┆ 0 │
│ 物凄い勢いでけーねが物凄いうた  ┆ MAS        ┆ 12.4     ┆ 東方Project  ┆ … ┆ 1421 ┆ 3 ┆ 0 ┆ 0 │
│ Campus mode!!                   ┆ MAS        ┆ 12.6     ┆ POPS & ANIME ┆ … ┆ 1940 ┆ 2 ┆ 0 ┆ 0 │
└─────────────────────────────────┴────────────┴──────────┴──────────────┴───┴──────┴───┴───┴───┘